In [276]:
!pip3 freeze | wc -l

51


In [277]:
import h5py

In [278]:
import os

In [279]:
import scipy.io

In [280]:
import numpy as np

In [281]:
path_just_generated = "/home/shuaman/video_sm/video_summarization/src/eccv16_dataset_cosum_google_pool5.h5"
# path_just_generated = "/home/shuaman/video_sm/DSNet/src/custom_dataset.h5"

In [282]:
#Air_Force_One_data = h5py.File(path_just_generated, 'r')['video_1']
data_all_cosum_mine = h5py.File(path_just_generated, 'r')

In [283]:
#path_data_preprocessd = "/data/shuaman/video_summarization/datasets/dsnet/datasets/eccv16_dataset_summe_google_pool5.h5"
# path_data_preprocessd = "/data/shuaman/video_summarization/datasets/object_features/eccv16_dataset_summe_google_pool5.h5"

In [284]:
# data_all_summe = h5py.File(path_data_preprocessd, 'r')

In [285]:
# list(data_all_summe)

In [286]:
for i in range(0,41):
#     video_gt = data_all_summe["video_" + str(i+1)]
    video_mine = data_all_cosum_mine["video_" + str(i+1)]
    
    perfect = True
    
    print(f'video {i+1} comparison')
    #if video_gt['features'][...].shape != video_mine['features'][...].shape:
     #   perfect = False
      #  print("features gt", video_gt['features'][...].shape)
    print("features mine", video_mine['features'][...].shape)
    print()
        
    #if video_gt['gtscore'][...].shape != video_mine['gtscore'][...].shape:
     #   perfect = False
      #  print("gtscore gt", video_gt['gtscore'][...].shape)
    print("gtscore mine", video_mine['gtscore'][...].shape)
    print()
        
    #print("video name gt", video_gt['video_name'][...])
    print("video name mine", video_mine['video_name'][...])
    
    #if video_gt['user_summary'][...].shape != video_mine['user_summary'][...].shape:
     #   perfect = False
      #  print("user summary gt", video_gt['user_summary'][...].shape)
    print("user summary mine", video_mine['user_summary'][...].shape)
    print()
        
    #if video_gt['n_frames'][...] != video_mine['n_frames'][...]:
     #   perfect = False
      #  print("n frames gt", video_gt['n_frames'][...])
    print("n frames mine", video_mine['n_frames'][...])
    print()
    
    #if video_gt['change_points'][...].shape != video_mine['change_points'][...].shape:  
     #   perfect = False
     #   print("change points gt", video_gt['change_points'][...].shape)
    print("change points mine", video_mine['change_points'][...].shape)
    print()
        
    #if video_gt['n_frame_per_seg'][...].shape != video_mine['n_frame_per_seg'][...].shape: 
     #   perfect = False
      #  print("n frame per seg gt", video_gt['n_frame_per_seg'][...].shape)
    print("n frame per seg mine", video_mine['n_frame_per_seg'][...].shape)
    print()
    
    #if video_gt['picks'][...].shape != video_mine['picks'][...].shape:
     #   perfect = False
      #  print("picks gt", video_gt['picks'][...].shape)
    print("picks mine", video_mine['picks'][...].shape)
    print()
        
    #if video_gt['n_steps'][...] != video_mine['n_steps'][...]:
     #   perfect = False
      #  print("n steps gt", video_gt['n_steps'][...])
    print("n steps mine", video_mine['n_steps'][...])
        
    #if perfect: 
     #   print("Everything is perfect")
    print()

video 1 comparison
features mine (566, 1024)

gtscore mine (566,)

video name mine b'Alana Blanchard Aloha Kauai - Alana Surfer Girl Ep 101'
user summary mine (3, 8479)

n frames mine 8479

change points mine (57, 2)

n frame per seg mine (57,)

picks mine (566,)

n steps mine 566

video 2 comparison
features mine (335, 1024)

gtscore mine (335,)

video name mine b'BKRW bikepolo TOURNAMENT x NIKE IAM1 PARIS Video'
user summary mine (3, 5017)

n frames mine 5017

change points mine (34, 2)

n frame per seg mine (34,)

picks mine (335,)

n steps mine 335

video 3 comparison
features mine (386, 1024)

gtscore mine (386,)

video name mine b"BUSTED by the Police, BASE Jumping in Benidorm Jokke Sommer's Barely Legal, Ep. 2"
user summary mine (3, 5777)

n frames mine 5777

change points mine (39, 2)

n frame per seg mine (39,)

picks mine (386,)

n steps mine 386

video 4 comparison
features mine (197, 1024)

gtscore mine (197,)

video name mine b'Bike Polo Part 1 Donnie'
user summary mine (3

# Evaluating a random video

In [320]:
#video 1
i = 2
#video_gt = data_all_summe["video_" + str(i+1)]
video_mine = data_all_cosum_mine["video_" + str(i+1)]

### Nombre

In [321]:
#print("video name gt", video_gt['video_name'][...])
print("video name mine", video_mine['video_name'][...])
print()


video name mine b"BUSTED by the Police, BASE Jumping in Benidorm Jokke Sommer's Barely Legal, Ep. 2"



In [322]:
str(video_mine['video_name'][...]) + "dasdas"

'b"BUSTED by the Police, BASE Jumping in Benidorm Jokke Sommer\'s Barely Legal, Ep. 2"dasdas'

### Features

In [323]:
# print("features gt", video_gt['features'][...].shape)
# video_gt['features'][...]

In [324]:
print("features mine", video_mine['features'][...].shape)
video_mine['features'][...]

features mine (386, 1024)


array([[0.        , 0.03725114, 0.31602007, ..., 0.        , 0.30105022,
        0.15761198],
       [0.0213535 , 0.00157479, 0.09606966, ..., 0.55955696, 1.5362637 ,
        0.33738583],
       [0.73355263, 0.08423016, 0.08643072, ..., 0.00659181, 1.3478322 ,
        0.3020863 ],
       ...,
       [0.22035797, 0.03781144, 0.01072673, ..., 0.26326963, 0.26689318,
        0.31510854],
       [0.06848811, 0.06972811, 0.        , ..., 0.0620455 , 0.34718555,
        0.02095653],
       [0.06848811, 0.06972811, 0.        , ..., 0.0620455 , 0.34718555,
        0.02095653]], dtype=float32)

### GTScore

In [325]:
# print("gtscore gt", video_gt['gtscore'][...].shape)
# video_gt['gtscore'][...]

In [326]:
print("gtscore mine", video_mine['gtscore'][...].shape)
video_mine['gtscore'][...]

gtscore mine (386,)


array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

### User summary

In [295]:
# print("user summary gt", video_gt['user_summary'][...].shape)
# video_gt['user_summary'][...]

In [296]:
print("user summary mine", video_mine['user_summary'][...].shape)
video_mine['user_summary'][...]

user summary mine (3, 8479)


array([[0., 0., 0., ..., 1., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

### N frames

In [297]:
# print("n frames gt", video_gt['n_frames'][...])

In [298]:
print("n frames mine", video_mine['n_frames'][...])

n frames mine 8479


### Change points

In [299]:
# print("change points gt", video_gt['change_points'][...].shape)
# video_gt['change_points'][...]

In [300]:
print("change points mine", video_mine['change_points'][...].shape)
video_mine['change_points'][...]

change points mine (57, 2)


array([[   0,  149],
       [ 150,  374],
       [ 375,  509],
       [ 510,  614],
       [ 615,  704],
       [ 705,  854],
       [ 855, 1259],
       [1260, 1589],
       [1590, 1679],
       [1680, 1829],
       [1830, 2054],
       [2055, 2129],
       [2130, 2294],
       [2295, 2444],
       [2445, 2564],
       [2565, 2609],
       [2610, 2669],
       [2670, 2729],
       [2730, 2774],
       [2775, 2819],
       [2820, 2954],
       [2955, 3209],
       [3210, 3539],
       [3540, 3614],
       [3615, 3929],
       [3930, 4109],
       [4110, 4259],
       [4260, 4319],
       [4320, 4559],
       [4560, 4664],
       [4665, 4754],
       [4755, 4844],
       [4845, 5009],
       [5010, 5129],
       [5130, 5204],
       [5205, 5294],
       [5295, 5384],
       [5385, 5549],
       [5550, 5759],
       [5760, 5819],
       [5820, 5864],
       [5865, 5924],
       [5925, 6119],
       [6120, 6224],
       [6225, 6299],
       [6300, 6509],
       [6510, 6569],
       [6570,

### N frames por segmenot

In [301]:
# print("n frame per seg gt", video_gt['n_frame_per_seg'][...].shape)
# video_gt['n_frame_per_seg'][...]

In [302]:
print("n frame per seg mine", video_mine['n_frame_per_seg'][...].shape)
video_mine['n_frame_per_seg'][...]

n frame per seg mine (57,)


array([150, 225, 135, 105,  90, 150, 405, 330,  90, 150, 225,  75, 165,
       150, 120,  45,  60,  60,  45,  45, 135, 255, 330,  75, 315, 180,
       150,  60, 240, 105,  90,  90, 165, 120,  75,  90,  90, 165, 210,
        60,  45,  60, 195, 105,  75, 210,  60, 120, 375,  60,  60, 255,
        90, 135, 240, 105, 469])

### Picks

In [303]:
# print("picks gt", video_gt['picks'][...].shape)
# video_gt['picks'][...]

In [304]:
print("picks mine", video_mine['picks'][...].shape)
video_mine['picks'][...]

picks mine (566,)


array([   0,   15,   30,   45,   60,   75,   90,  105,  120,  135,  150,
        165,  180,  195,  210,  225,  240,  255,  270,  285,  300,  315,
        330,  345,  360,  375,  390,  405,  420,  435,  450,  465,  480,
        495,  510,  525,  540,  555,  570,  585,  600,  615,  630,  645,
        660,  675,  690,  705,  720,  735,  750,  765,  780,  795,  810,
        825,  840,  855,  870,  885,  900,  915,  930,  945,  960,  975,
        990, 1005, 1020, 1035, 1050, 1065, 1080, 1095, 1110, 1125, 1140,
       1155, 1170, 1185, 1200, 1215, 1230, 1245, 1260, 1275, 1290, 1305,
       1320, 1335, 1350, 1365, 1380, 1395, 1410, 1425, 1440, 1455, 1470,
       1485, 1500, 1515, 1530, 1545, 1560, 1575, 1590, 1605, 1620, 1635,
       1650, 1665, 1680, 1695, 1710, 1725, 1740, 1755, 1770, 1785, 1800,
       1815, 1830, 1845, 1860, 1875, 1890, 1905, 1920, 1935, 1950, 1965,
       1980, 1995, 2010, 2025, 2040, 2055, 2070, 2085, 2100, 2115, 2130,
       2145, 2160, 2175, 2190, 2205, 2220, 2235, 22

### Steps

In [305]:
# print("n steps gt", video_gt['n_steps'][...])
# video_gt['n_steps'][...]

In [306]:
print("n steps mine", video_mine['n_steps'][...])
video_mine['n_steps'][...]

n steps mine 566


array(566)

In [106]:
import numpy as np
import os
import pandas as pd
import cv2

In [115]:
path_data = "/data/shuaman/video_summarization/datasets/raw_datasets/CoSum"

In [116]:
path_shots = os.path.join(path_data, "shots")
path_shots

'/data/shuaman/video_summarization/datasets/raw_datasets/CoSum/shots'

In [117]:
path_annotations = os.path.join(path_data, "annotation")
path_annotations

'/data/shuaman/video_summarization/datasets/raw_datasets/CoSum/annotation'

In [118]:
path_videos = os.path.join(path_data, "videos")
path_videos

'/data/shuaman/video_summarization/datasets/raw_datasets/CoSum/videos'

In [130]:
dataset = pd.read_excel(path_data+"/dataset.xlsx",engine='openpyxl')

In [131]:
dataset = dataset.loc[dataset["DOWNLOADED"]==1].reset_index(drop=True)

In [132]:
dataset.head(2)

ID                                              VIDEO  \
0   1               Burj Khalifa Pinnacle BASE Jump - 4K   
1   2  Mat Zo feat. Linnea Schossow - The Sky (OFFICI...   

                                     VIDEO_URL VIDEO_CATEGORY  DOWNLOADED  \
0  https://www.youtube.com/watch?v=iD4qsWnjsNU   01_base_jump           1   
1  https://www.youtube.com/watch?v=iMCcnA9ifqg   01_base_jump           1   

  SHORT CATEGORY  VIDEO_ID_IN_CATEGORY  
0           base                     1  
1           base                     2

In [240]:
sorted(list(dataset[["VIDEO_CATEGORY","SHORT CATEGORY",
                                                    "VIDEO_ID_IN_CATEGORY","VIDEO"]].drop_duplicates().values),
                                        key=lambda x: x[-1], reverse=False)

[array(['10_surfing', 'surf', 3,
        'Alana Blanchard Aloha Kauai - Alana Surfer Girl Ep 101'],
       dtype=object),
 array(['02_bike_polo', 'bike', 4,
        'BKRW bikepolo TOURNAMENT x NIKE IAM1 PARIS Video'], dtype=object),
 array(['01_base_jump', 'base', 3,
        "BUSTED by the Police, BASE Jumping in Benidorm Jokke Sommer's Barely Legal, Ep. 2"],
       dtype=object),
 array(['02_bike_polo', 'bike', 5, 'Bike Polo Part 1 Donnie'], dtype=object),
 array(['01_base_jump', 'base', 1, 'Burj Khalifa Pinnacle BASE Jump - 4K'],
       dtype=object),
 array(['03_eiffel_tower', 'eiffel', 4, 'Eiffel Tower'], dtype=object),
 array(['03_eiffel_tower', 'eiffel', 3, 'Eiffel Tower Time Lapse'],
       dtype=object),
 array(['04_excavators_river_xing', 'exca', 3,
        'Excavator Extravaganza How to cross river with two excavators'],
       dtype=object),
 array(['02_bike_polo', 'bike', 1, 'Freak Scene Bike Polo Part 1 The Gear'],
       dtype=object),
 array(['10_surfing', 'surf', 5, 'Go

In [267]:
xdd = sorted(list(dataset[["VIDEO_CATEGORY","SHORT CATEGORY","VIDEO_ID_IN_CATEGORY","VIDEO"]].drop_duplicates().values), key=lambda x: x[-1]+".mp4", reverse=False)

In [268]:
video_list = [videoname for videoname in os.listdir("/data/shuaman/video_summarization/datasets/raw_datasets/CoSum/videos") if videoname.lower().endswith(".mp4")]
sorted(video_list, reverse=False)

['Alana Blanchard Aloha Kauai - Alana Surfer Girl Ep 101.mp4',
 'BKRW bikepolo TOURNAMENT x NIKE IAM1 PARIS Video.mp4',
 "BUSTED by the Police, BASE Jumping in Benidorm Jokke Sommer's Barely Legal, Ep. 2.mp4",
 'Bike Polo Part 1 Donnie.mp4',
 'Burj Khalifa Pinnacle BASE Jump - 4K.mp4',
 'Eiffel Tower Time Lapse.mp4',
 'Eiffel Tower.mp4',
 'Excavator Extravaganza How to cross river with two excavators.mp4',
 'Freak Scene Bike Polo Part 1 The Gear.mp4',
 'Go Pro Surfing Sexy Girl Compilation.mp4',
 'How was the Eiffel Tower built I Head Squeeze.mp4',
 'Ichiro slugs his first homer of the season in 2014.mp4',
 'Kids Playing with Leaves.mp4',
 'Kids playing in leaves.mp4',
 'Mat Zo feat. Linnea Schossow - The Sky (OFFICIAL MUSIC VIDEO).mp4',
 "Mother's Day MLB News Story.mp4",
 'NYC-Bike Polo.mp4',
 "New York City's Statue of Liberty - 2 Minute Tour.mp4",
 'Notre Dame Football 2014-15 Pump Up.mp4',
 'Notre Dame Football 2014.mp4',
 'Orlando Bike Polo.mp4',
 'Paper Model of the Statue of Li

In [269]:
xdd

[array(['10_surfing', 'surf', 3,
        'Alana Blanchard Aloha Kauai - Alana Surfer Girl Ep 101'],
       dtype=object),
 array(['02_bike_polo', 'bike', 4,
        'BKRW bikepolo TOURNAMENT x NIKE IAM1 PARIS Video'], dtype=object),
 array(['01_base_jump', 'base', 3,
        "BUSTED by the Police, BASE Jumping in Benidorm Jokke Sommer's Barely Legal, Ep. 2"],
       dtype=object),
 array(['02_bike_polo', 'bike', 5, 'Bike Polo Part 1 Donnie'], dtype=object),
 array(['01_base_jump', 'base', 1, 'Burj Khalifa Pinnacle BASE Jump - 4K'],
       dtype=object),
 array(['03_eiffel_tower', 'eiffel', 3, 'Eiffel Tower Time Lapse'],
       dtype=object),
 array(['03_eiffel_tower', 'eiffel', 4, 'Eiffel Tower'], dtype=object),
 array(['04_excavators_river_xing', 'exca', 3,
        'Excavator Extravaganza How to cross river with two excavators'],
       dtype=object),
 array(['02_bike_polo', 'bike', 1, 'Freak Scene Bike Polo Part 1 The Gear'],
       dtype=object),
 array(['10_surfing', 'surf', 5, 'Go

In [253]:
a = ["z","a"]
a.sort()

In [254]:
a

['a', 'z']

In [230]:
c

1

In [221]:
for x,y,z in dataset[["VIDEO_CATEGORY","SHORT CATEGORY","VIDEO_ID_IN_CATEGORY"]].drop_duplicates().values:
    print(x, y,z)

01_base_jump base 1
01_base_jump base 2
01_base_jump base 3
01_base_jump base 4
01_base_jump base 5
02_bike_polo bike 1
02_bike_polo bike 2
02_bike_polo bike 3
02_bike_polo bike 4
02_bike_polo bike 5
03_eiffel_tower eiffel 3
03_eiffel_tower eiffel 4
03_eiffel_tower eiffel 5
03_eiffel_tower eiffel 7
04_excavators_river_xing exca 3
05_kids_playing_in_leaves kids 1
05_kids_playing_in_leaves kids 2
05_kids_playing_in_leaves kids 3
05_kids_playing_in_leaves kids 5
05_kids_playing_in_leaves kids 6
06_mlb mlb 1
06_mlb mlb 2
06_mlb mlb 4
06_mlb mlb 5
06_mlb mlb 6
07_nfl nfl 1
07_nfl nfl 2
07_nfl nfl 3
08_notre_dame_cathedral notre 1
08_notre_dame_cathedral notre 2
08_notre_dame_cathedral notre 4
09_statue_of_liberty statue 2
09_statue_of_liberty statue 3
09_statue_of_liberty statue 4
09_statue_of_liberty statue 5
10_surfing surf 1
10_surfing surf 2
10_surfing surf 3
10_surfing surf 4
10_surfing surf 5
10_surfing surf 6


In [133]:
dataset.shape

(41, 7)

In [134]:
dataset["VIDEO_CATEGORY"].value_counts()

10_surfing                   6
01_base_jump                 5
05_kids_playing_in_leaves    5
02_bike_polo                 5
06_mlb                       5
09_statue_of_liberty         4
03_eiffel_tower              4
08_notre_dame_cathedral      3
07_nfl                       3
04_excavators_river_xing     1
Name: VIDEO_CATEGORY, dtype: int64

In [135]:
for x,y in dataset[["VIDEO_CATEGORY","SHORT CATEGORY"]].drop_duplicates().values:
    print(x, y)

01_base_jump base
02_bike_polo bike
03_eiffel_tower eiffel
04_excavators_river_xing exca
05_kids_playing_in_leaves kids
06_mlb mlb
07_nfl nfl
08_notre_dame_cathedral notre
09_statue_of_liberty statue
10_surfing surf


In [136]:
dataset.loc[dataset["VIDEO_CATEGORY"]=="01_base_jump",["VIDEO_ID_IN_CATEGORY", "VIDEO"]].drop_duplicates().values

array([[1, 'Burj Khalifa Pinnacle BASE Jump - 4K'],
       [2,
        'Mat Zo feat. Linnea Schossow - The Sky (OFFICIAL MUSIC VIDEO)'],
       [3,
        "BUSTED by the Police, BASE Jumping in Benidorm Jokke Sommer's Barely Legal, Ep. 2"],
       [4, "World's First Wingsuit BASE Jumping Dog"],
       [5, "World's Highest BASE Jump - Flying from Mt. Everest"]],
      dtype=object)

In [137]:
/data/shuaman/video_summarization/datasets/raw_datasets/CoSum/videos/BUSTED by the Police, BASE Jumping in Benidorm | Jokke Sommer's Barely Legal, Ep. 2.mp4

SyntaxError: invalid syntax (4242225047.py, line 1)

In [138]:
xd = cv2.VideoCapture("/data/shuaman/video_summarization/datasets/raw_datasets/CoSum/videos/BUSTED by the Police, BASE Jumping in Benidorm Jokke Sommer's Barely Legal, Ep. 2.mp4")

In [139]:
xd.get(cv2.CAP_PROP_FRAME_COUNT)

5777.0

In [165]:
[1, 2, 6, 5 ]* 5

[1, 2, 6, 5, 1, 2, 6, 5, 1, 2, 6, 5, 1, 2, 6, 5, 1, 2, 6, 5]

In [216]:
for category, short_name in dataset[["VIDEO_CATEGORY","SHORT CATEGORY"]].drop_duplicates().values:
    path_ant_category = os.path.join(path_annotations,category)
    path_shots_category = os.path.join(path_shots,category)
    
    list_videos = dataset.loc[dataset["VIDEO_CATEGORY"]==category,["VIDEO_ID_IN_CATEGORY", "VIDEO"]].drop_duplicates().values
    print(category)
    #print(list_videos)
    for video_id, video_name in list_videos:
        
        shots = open(os.path.join(path_shots_category, f'{short_name}{video_id}_shots.txt'),'r')
        print(video_id)
        print(os.path.join(path_videos, f'{video_name}.mp4'))
        video = cv2.VideoCapture(os.path.join(path_videos, f'{video_name}.mp4'))
        user1 = scipy.io.loadmat(os.path.join(path_ant_category, f'{video_id}__dualplus.mat'))["labels"][:,0] 
        user2 = scipy.io.loadmat(os.path.join(path_ant_category, f'{video_id}__kk.mat'))["labels"][:,0]
        user3 = scipy.io.loadmat(os.path.join(path_ant_category, f'{video_id}__vv.mat'))["labels"][:,0]
        
        n_frames = int(video.get(cv2.CAP_PROP_FRAME_COUNT))
        new_gt_user_1 = np.zeros(n_frames)
        
        shots = shots.read().splitlines()
        #print(shots)
        #shots = [int(shots[0]) if shots[0]=='1' else int(int(shots[0])*n_frames/int(shots[-1]))] + [int(int(nframe)*n_frames/int(shots[-1])) for nframe in shots[1:]]
        shots = [int(np.ceil(int(nframe)*n_frames/int(shots[-1]))) for nframe in shots]
        
        #shots = shots[0] + shots[1:]*(n_frames/shots[-1]) 
        #print(shots)
        print(shots[-1])
        print(n_frames)
        for indexshot in user1:
            #print(indexshot)
            if indexshot >= len(shots):
                indexshot = len(shots)-1
            #print(indexshot)
            new_gt_user_1[int(shots[int(indexshot)-1])-1:int(shots[int(indexshot)])-1] = 1
        
        print(new_gt_user_1.shape)
        print(new_gt_user_1.sum())
        print(new_gt_user_1)
        
        
        #break
    #break
    print("done")
    print()
    #print(os.listdir(path_ant_category))
    #print(os.path.join(path_shots,category))

01_base_jump
1
/data/shuaman/video_summarization/datasets/raw_datasets/CoSum/videos/Burj Khalifa Pinnacle BASE Jump - 4K.mp4
2551
2551
(2551,)
1039.0
[0. 0. 0. ... 0. 0. 0.]
2
/data/shuaman/video_summarization/datasets/raw_datasets/CoSum/videos/Mat Zo feat. Linnea Schossow - The Sky (OFFICIAL MUSIC VIDEO).mp4
5703
5703
(5703,)
5476.0
[1. 1. 1. ... 1. 1. 0.]
3
/data/shuaman/video_summarization/datasets/raw_datasets/CoSum/videos/BUSTED by the Police, BASE Jumping in Benidorm Jokke Sommer's Barely Legal, Ep. 2.mp4
5777
5777
(5777,)
766.0
[0. 0. 0. ... 0. 0. 0.]
4
/data/shuaman/video_summarization/datasets/raw_datasets/CoSum/videos/World's First Wingsuit BASE Jumping Dog.mp4
1386
1386
(1386,)
233.0
[0. 0. 0. ... 0. 0. 0.]
5
/data/shuaman/video_summarization/datasets/raw_datasets/CoSum/videos/World's Highest BASE Jump - Flying from Mt. Everest.mp4
2159
2159
(2159,)
405.0
[0. 0. 0. ... 0. 0. 0.]
done

02_bike_polo
1
/data/shuaman/video_summarization/datasets/raw_datasets/CoSum/videos/Freak S

In [158]:
722*5545/722

5545.0

In [157]:
5545*1/722

7.68005540166205

In [217]:
mat = scipy.io.loadmat("/data/shuaman/video_summarization/datasets/raw_datasets/CoSum/annotation/01_base_jump/2__dualplus.mat") 

In [218]:
#SumMe
mat.keys()

dict_keys(['__header__', '__version__', '__globals__', 'labels'])

In [219]:
mat["labels"]

array([[ 1,  1],
       [ 3,  1],
       [ 4,  1],
       [ 5,  1],
       [ 6,  1],
       [ 8,  1],
       [10,  1],
       [11,  1],
       [12,  1],
       [13,  1],
       [14,  1],
       [15,  1],
       [16,  1],
       [17,  1],
       [18,  1],
       [19,  1],
       [20,  1],
       [21,  1],
       [23,  1],
       [24,  1],
       [25,  1],
       [26,  1],
       [27,  1],
       [28,  1],
       [29,  1],
       [30,  1],
       [31,  1],
       [32,  1],
       [33,  1],
       [34,  1],
       [35,  1],
       [36,  1],
       [37,  1],
       [38,  1],
       [39,  1],
       [40,  1],
       [41,  1],
       [42,  1],
       [43,  1],
       [44,  1],
       [46,  1],
       [47,  1],
       [48,  1],
       [49,  1],
       [50,  1],
       [51,  1],
       [52,  1],
       [54,  1],
       [55,  1],
       [56,  1],
       [57,  1],
       [58,  1],
       [59,  1],
       [60,  1],
       [61,  1],
       [62,  1],
       [63,  1],
       [64,  1],
       [65,  1

In [179]:
for i in mat["labels"][:,0]:
    print(i)

7
8
12
16
