In [1]:
!pip3 freeze | wc -l

83


In [2]:
import h5py

In [3]:
import scipy.io

In [4]:
import numpy as np

In [8]:
# path_just_generated = "/home/shuaman/video_sm/video_summarization/src/eccv16_dataset_summe_google_pool5.h5"
path_just_generated = "/data/shuaman/video_summarization/datasets/processed_datasets/dataset_summe_processed.h5"

In [9]:
#Air_Force_One_data = h5py.File(path_just_generated, 'r')['video_1']
data_all_summe_mine = h5py.File(path_just_generated, 'r')

In [10]:
#path_data_preprocessd = "/data/shuaman/video_summarization/datasets/dsnet/datasets/eccv16_dataset_summe_google_pool5.h5"
path_data_preprocessd = "/data/shuaman/video_summarization/datasets/object_features/eccv16_dataset_summe_google_pool5.h5"

In [11]:
data_all_summe = h5py.File(path_data_preprocessd, 'r')

In [12]:
# list(data_all_summe)

In [13]:
for i in range(0,25):
    video_gt = data_all_summe["video_" + str(i+1)]
    video_mine = data_all_summe_mine["video_" + str(i+1)]
    
    perfect = True
    
    print(f'video {i+1} comparison')
    if video_gt['features'][...].shape != video_mine['features'][...].shape:
        perfect = False
        print("features gt", video_gt['features'][...].shape)
        print("features mine", video_mine['features'][...].shape)
        print()
        
    if video_gt['features_rn'][...].shape != video_mine['features_rn'][...].shape:
        perfect = False
        print("features_rn gt", video_gt['features_rn'][...].shape)
        print("features_rn mine", video_mine['features_rn'][...].shape)
        print()
        
    if video_gt['features_iv3'][...].shape != video_mine['features_iv3'][...].shape:
        perfect = False
        print("features_iv3 gt", video_gt['features_iv3'][...].shape)
        print("features_iv3 mine", video_mine['features_iv3'][...].shape)
        print()
        
    if video_gt['features_3D'][...].shape != video_mine['features_3D'][...].shape:
        perfect = False
        print("features_3D gt", video_gt['features_3D'][...].shape)
        print("features_3D mine", video_mine['features_3D'][...].shape)
        print()
        
    if video_gt['gtscore'][...].shape != video_mine['gtscore'][...].shape:
        perfect = False
        print("gtscore gt", video_gt['gtscore'][...].shape)
        print("gtscore mine", video_mine['gtscore'][...].shape)
        print()
        
    print("video name gt", video_gt['video_name'][...])
    print("video name mine", video_mine['video_name'][...])
    
    if video_gt['user_summary'][...].shape != video_mine['user_summary'][...].shape:
        perfect = False
        print("user summary gt", video_gt['user_summary'][...].shape)
        print("user summary mine", video_mine['user_summary'][...].shape)
        print()
        
    if video_gt['n_frames'][...] != video_mine['n_frames'][...]:
        perfect = False
        print("n frames gt", video_gt['n_frames'][...])
        print("n frames mine", video_mine['n_frames'][...])
        print()
    if video_gt['change_points'][...].shape != video_mine['change_points'][...].shape:  
        perfect = False
        print("change points gt", video_gt['change_points'][...].shape)
        print("change points mine", video_mine['change_points'][...].shape)
        print()
        
    if video_gt['n_frame_per_seg'][...].shape != video_mine['n_frame_per_seg'][...].shape: 
        perfect = False
        print("n frame per seg gt", video_gt['n_frame_per_seg'][...].shape)
        print("n frame per seg mine", video_mine['n_frame_per_seg'][...].shape)
        print()
    
    if video_gt['picks'][...].shape != video_mine['picks'][...].shape:
        perfect = False
        print("picks gt", video_gt['picks'][...].shape)
        print("picks mine", video_mine['picks'][...].shape)
        print()
        
    if video_gt['n_steps'][...] != video_mine['n_steps'][...]:
        perfect = False
        print("n steps gt", video_gt['n_steps'][...])
        print("n steps mine", video_mine['n_steps'][...])
        
    print("features_rgb gt", video_gt['features_rgb'][...].shape)
    print("features_rgb mine", video_mine['features_rgb'][...].shape)
    print("features_flow gt", video_gt['features_flow'][...].shape)
    print("features_flow mine", video_mine['features_flow'][...].shape)
        
    if perfect: 
        print("Everything is perfect")
        print()

video 1 comparison
video name gt b'Air_Force_One'
video name mine b'Air_Force_One'
features_rgb gt (4478, 1024)
features_rgb mine (284, 1024)
features_flow gt (4477, 1024)
features_flow mine (283, 1024)
Everything is perfect

video 2 comparison
video name gt b'Base jumping'
video name mine b'Base jumping'
features_rgb gt (4713, 1024)
features_rgb mine (300, 1024)
features_flow gt (4712, 1024)
features_flow mine (299, 1024)
Everything is perfect

video 3 comparison
video name gt b'Bearpark_climbing'
video name mine b'Bearpark_climbing'
features_rgb gt (3325, 1024)
features_rgb mine (207, 1024)
features_flow gt (3324, 1024)
features_flow mine (206, 1024)
Everything is perfect

video 4 comparison
video name gt b'Bike Polo'
video name mine b'Bike Polo'
features_rgb gt (3048, 1024)
features_rgb mine (189, 1024)
features_flow gt (3047, 1024)
features_flow mine (188, 1024)
Everything is perfect

video 5 comparison
video name gt b'Bus_in_Rock_Tunnel'
video name mine b'Bus_in_Rock_Tunnel'
featu

# Evaluating a random video

In [14]:
#video 1
i = 0
video_gt = data_all_summe["video_" + str(i+1)]
video_mine = data_all_summe_mine["video_" + str(i+1)]

### Nombre

In [15]:
    print("video name gt", video_gt['video_name'][...])
    print("video name mine", video_mine['video_name'][...])
    print()


video name gt b'Air_Force_One'
video name mine b'Air_Force_One'



In [16]:
str(video_mine['video_name'][...]) + "dasdas"

"b'Air_Force_One'dasdas"

### Features

In [29]:
video_gt['features_3D'][...]

array([[1.4449841 , 0.91934365, 1.1335695 , ..., 0.9544913 , 1.4337465 ,
        1.0540687 ],
       [1.4518617 , 0.86280346, 1.1453713 , ..., 0.9640655 , 1.4517524 ,
        1.0513854 ],
       [1.4863755 , 0.954107  , 1.1712769 , ..., 0.9775462 , 1.484416  ,
        1.0180132 ],
       ...,
       [1.788697  , 1.0815034 , 1.3588432 , ..., 1.2724972 , 1.060129  ,
        0.8041994 ],
       [1.7182093 , 0.9637469 , 1.2734638 , ..., 1.2688835 , 1.1332316 ,
        0.8860217 ],
       [1.6690913 , 1.020613  , 1.2163559 , ..., 1.2730529 , 1.2078943 ,
        0.8786451 ]], dtype=float32)

In [30]:
video_mine['features_3D'][...]

array([[1.4449841 , 0.91934365, 1.1335695 , ..., 0.9544913 , 1.4337465 ,
        1.0540687 ],
       [1.4518617 , 0.86280346, 1.1453713 , ..., 0.9640655 , 1.4517524 ,
        1.0513854 ],
       [1.4863755 , 0.954107  , 1.1712769 , ..., 0.9775462 , 1.484416  ,
        1.0180132 ],
       ...,
       [1.788697  , 1.0815034 , 1.3588432 , ..., 1.2724972 , 1.060129  ,
        0.8041994 ],
       [1.7182093 , 0.9637469 , 1.2734638 , ..., 1.2688835 , 1.1332316 ,
        0.8860217 ],
       [1.6690913 , 1.020613  , 1.2163559 , ..., 1.2730529 , 1.2078943 ,
        0.8786451 ]], dtype=float32)

In [31]:
print("features gt", video_gt['features'][...].shape)
video_gt['features'][...]

features gt (300, 1024)


array([[0.00000000e+00, 0.00000000e+00, 3.61840939e-04, ...,
        1.02224345e-04, 2.28259116e-02, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 3.40301369e-04, ...,
        3.51528870e-03, 4.94062938e-02, 0.00000000e+00],
       [0.00000000e+00, 5.40758716e-04, 2.82520137e-04, ...,
        4.78237853e-05, 2.36145183e-02, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 1.80268151e-04, ...,
        3.99936456e-03, 2.72235880e-03, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.11069101e-04, ...,
        1.36979891e-03, 1.36739679e-03, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.44374644e-04, ...,
        2.81268102e-03, 8.94312747e-03, 0.00000000e+00]], dtype=float32)

In [32]:
print("features mine", video_mine['features'][...].shape)
video_mine['features'][...]

features mine (300, 1024)


array([[0.6004027 , 0.61960006, 0.10456449, ..., 0.37872282, 0.60464656,
        0.41944176],
       [0.6537041 , 0.8070306 , 0.10086088, ..., 0.27387536, 0.4955928 ,
        0.38311753],
       [0.6249571 , 0.7906894 , 0.15495808, ..., 0.3807661 , 0.54797375,
        0.44711748],
       ...,
       [0.32719967, 0.7071626 , 0.08081598, ..., 0.39858565, 0.44998378,
        0.5115156 ],
       [0.3921509 , 0.64381135, 0.08239483, ..., 0.33968228, 0.43223944,
        0.5529209 ],
       [0.34564772, 0.6743997 , 0.09874789, ..., 0.47167143, 0.42363653,
        0.5529467 ]], dtype=float32)

### GTScore

In [33]:
print("gtscore gt", video_gt['gtscore'][...].shape)
video_gt['gtscore'][...]

gtscore gt (300,)


array([0.        , 0.        , 0.        , 0.        , 0.06666667,
       0.06666667, 0.06666667, 0.06666667, 0.13333334, 0.13333334,
       0.13333334, 0.13333334, 0.06666667, 0.06666667, 0.13333334,
       0.06666667, 0.13333334, 0.13333334, 0.06666667, 0.2       ,
       0.13333334, 0.13333334, 0.13333334, 0.06666667, 0.06666667,
       0.        , 0.06666667, 0.06666667, 0.13333334, 0.06666667,
       0.06666667, 0.06666667, 0.06666667, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.06666667, 0.06666667, 0.13333334, 0.13333334,
       0.06666667, 0.        , 0.06666667, 0.06666667, 0.06666667,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.06666

In [34]:
print("gtscore mine", video_mine['gtscore'][...].shape)
video_mine['gtscore'][...]

gtscore mine (300,)


array([0.        , 0.        , 0.        , 0.        , 0.06666667,
       0.06666667, 0.06666667, 0.06666667, 0.13333334, 0.13333334,
       0.13333334, 0.13333334, 0.06666667, 0.06666667, 0.13333334,
       0.06666667, 0.13333334, 0.13333334, 0.06666667, 0.2       ,
       0.13333334, 0.13333334, 0.13333334, 0.06666667, 0.06666667,
       0.        , 0.06666667, 0.06666667, 0.13333334, 0.06666667,
       0.06666667, 0.06666667, 0.06666667, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.06666667, 0.06666667, 0.13333334, 0.13333334,
       0.06666667, 0.        , 0.06666667, 0.06666667, 0.06666667,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.06666

In [35]:
import numpy as np

In [36]:
np.all(video_gt['gtscore'][...]==video_mine['gtscore'][...])

True

### User summary

In [37]:
print("user summary gt", video_gt['user_summary'][...].shape)
video_gt['user_summary'][...]

user summary gt (15, 4494)


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [38]:
video_gt['user_summary'][...].sum()

9399.0

In [39]:
print("user summary mine", video_mine['user_summary'][...].shape)
video_mine['user_summary'][...]

user summary mine (15, 4494)


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [40]:
video_mine['user_summary'][...].sum()

9399.0

In [41]:
np.all(video_gt['user_summary'][...]==video_mine['user_summary'][...])

True

### N frames

In [42]:
print("n frames gt", video_gt['n_frames'][...])

n frames gt 4494


In [43]:
print("n frames mine", video_mine['n_frames'][...])

n frames mine 4494


### Change points

In [44]:
print("change points gt", video_gt['change_points'][...].shape)
video_gt['change_points'][...]

change points gt (30, 2)


array([[   0,  244],
       [ 245,  473],
       [ 474,  827],
       [ 828, 1081],
       [1082, 1233],
       [1234, 1438],
       [1439, 1530],
       [1531, 1642],
       [1643, 1796],
       [1797, 1973],
       [1974, 1998],
       [1999, 2110],
       [2111, 2403],
       [2404, 2539],
       [2540, 2664],
       [2665, 2908],
       [2909, 3160],
       [3161, 3370],
       [3371, 3521],
       [3522, 3649],
       [3650, 3899],
       [3900, 3940],
       [3941, 3990],
       [3991, 4034],
       [4035, 4079],
       [4080, 4138],
       [4139, 4228],
       [4229, 4285],
       [4286, 4342],
       [4343, 4493]])

In [45]:
print("change points mine", video_mine['change_points'][...].shape)
video_mine['change_points'][...]

change points mine (30, 2)


array([[   0,  389],
       [ 390,  929],
       [ 930, 1319],
       [1320, 1559],
       [1560, 1694],
       [1695, 1904],
       [1905, 2069],
       [2070, 2234],
       [2235, 2414],
       [2415, 2654],
       [2655, 2819],
       [2820, 2984],
       [2985, 3134],
       [3135, 3239],
       [3240, 3344],
       [3345, 3419],
       [3420, 3524],
       [3525, 3659],
       [3660, 3734],
       [3735, 3854],
       [3855, 3899],
       [3900, 3944],
       [3945, 3989],
       [3990, 4034],
       [4035, 4094],
       [4095, 4154],
       [4155, 4214],
       [4215, 4259],
       [4260, 4289],
       [4290, 4493]])

### N frames por segmenot

In [46]:
print("n frame per seg gt", video_gt['n_frame_per_seg'][...].shape)
video_gt['n_frame_per_seg'][...]

n frame per seg gt (30,)


array([245, 229, 354, 254, 152, 205,  92, 112, 154, 177,  25, 112, 293,
       136, 125, 244, 252, 210, 151, 128, 250,  41,  50,  44,  45,  59,
        90,  57,  57, 151])

In [47]:
print("n frame per seg mine", video_mine['n_frame_per_seg'][...].shape)
video_mine['n_frame_per_seg'][...]

n frame per seg mine (30,)


array([390, 540, 390, 240, 135, 210, 165, 165, 180, 240, 165, 165, 150,
       105, 105,  75, 105, 135,  75, 120,  45,  45,  45,  45,  60,  60,
        60,  45,  30, 204])

### Picks

In [48]:
print("picks gt", video_gt['picks'][...].shape)
video_gt['picks'][...]

picks gt (300,)


array([   0,   15,   30,   45,   60,   75,   90,  105,  120,  135,  150,
        165,  180,  195,  210,  225,  240,  255,  270,  285,  300,  315,
        330,  345,  360,  375,  390,  405,  420,  435,  450,  465,  480,
        495,  510,  525,  540,  555,  570,  585,  600,  615,  630,  645,
        660,  675,  690,  705,  720,  735,  750,  765,  780,  795,  810,
        825,  840,  855,  870,  885,  900,  915,  930,  945,  960,  975,
        990, 1005, 1020, 1035, 1050, 1065, 1080, 1095, 1110, 1125, 1140,
       1155, 1170, 1185, 1200, 1215, 1230, 1245, 1260, 1275, 1290, 1305,
       1320, 1335, 1350, 1365, 1380, 1395, 1410, 1425, 1440, 1455, 1470,
       1485, 1500, 1515, 1530, 1545, 1560, 1575, 1590, 1605, 1620, 1635,
       1650, 1665, 1680, 1695, 1710, 1725, 1740, 1755, 1770, 1785, 1800,
       1815, 1830, 1845, 1860, 1875, 1890, 1905, 1920, 1935, 1950, 1965,
       1980, 1995, 2010, 2025, 2040, 2055, 2070, 2085, 2100, 2115, 2130,
       2145, 2160, 2175, 2190, 2205, 2220, 2235, 22

In [49]:
print("picks mine", video_mine['picks'][...].shape)
video_mine['picks'][...]

picks mine (300,)


array([   0,   15,   30,   45,   60,   75,   90,  105,  120,  135,  150,
        165,  180,  195,  210,  225,  240,  255,  270,  285,  300,  315,
        330,  345,  360,  375,  390,  405,  420,  435,  450,  465,  480,
        495,  510,  525,  540,  555,  570,  585,  600,  615,  630,  645,
        660,  675,  690,  705,  720,  735,  750,  765,  780,  795,  810,
        825,  840,  855,  870,  885,  900,  915,  930,  945,  960,  975,
        990, 1005, 1020, 1035, 1050, 1065, 1080, 1095, 1110, 1125, 1140,
       1155, 1170, 1185, 1200, 1215, 1230, 1245, 1260, 1275, 1290, 1305,
       1320, 1335, 1350, 1365, 1380, 1395, 1410, 1425, 1440, 1455, 1470,
       1485, 1500, 1515, 1530, 1545, 1560, 1575, 1590, 1605, 1620, 1635,
       1650, 1665, 1680, 1695, 1710, 1725, 1740, 1755, 1770, 1785, 1800,
       1815, 1830, 1845, 1860, 1875, 1890, 1905, 1920, 1935, 1950, 1965,
       1980, 1995, 2010, 2025, 2040, 2055, 2070, 2085, 2100, 2115, 2130,
       2145, 2160, 2175, 2190, 2205, 2220, 2235, 22

### Steps

In [50]:
print("n steps gt", video_gt['n_steps'][...])
video_gt['n_steps'][...]

n steps gt 300


array(300)

In [51]:
print("n steps mine", video_mine['n_steps'][...])
video_mine['n_steps'][...]

n steps mine 300


array(300)

### Features rn

In [52]:
print("features_rn", video_mine['features_rn'][...].shape)
video_mine['features_rn'][...]

features_rn (300, 2048)


array([[1.553214  , 1.0433971 , 0.17686906, ..., 0.22757381, 0.17993514,
        0.1575417 ],
       [1.4664333 , 0.91867715, 0.19714923, ..., 0.1466809 , 0.15695298,
        0.15399107],
       [1.4085718 , 1.0036252 , 0.17554843, ..., 0.15646867, 0.19293544,
        0.12661326],
       ...,
       [1.6480887 , 0.93125993, 0.28589782, ..., 0.18681616, 0.05278997,
        0.12568215],
       [1.3323303 , 0.9370804 , 0.20901115, ..., 0.13248262, 0.101122  ,
        0.14797306],
       [1.4676307 , 0.9199309 , 0.25544637, ..., 0.20894389, 0.04304835,
        0.13302596]], dtype=float32)

### Features iv3

In [53]:
print("features_iv3", video_mine['features_iv3'][...].shape)
video_mine['features_iv3'][...]

features_iv3 (300, 2048)


array([[0.21234429, 0.10265395, 0.59338117, ..., 0.06408925, 0.28995377,
        0.026103  ],
       [0.2292571 , 0.07883335, 0.5774566 , ..., 0.05655143, 0.2694677 ,
        0.04212337],
       [0.21867427, 0.07945217, 0.6102948 , ..., 0.06824115, 0.46176663,
        0.0316253 ],
       ...,
       [0.12570012, 0.06743427, 0.52873176, ..., 0.12259689, 0.2427927 ,
        0.07099357],
       [0.15925121, 0.12825719, 0.519825  , ..., 0.12426585, 0.2658464 ,
        0.04829255],
       [0.12718542, 0.08536571, 0.56597877, ..., 0.0894423 , 0.3253884 ,
        0.08726559]], dtype=float32)

### Features RGB

In [54]:
print("features_rgb", video_mine['features_rgb'][...].shape)
video_mine['features_rgb'][...]

features_rgb (284, 1024)


array([[0.18277001, 0.36297634, 0.1910125 , ..., 0.16239814, 0.10009093,
        0.5688831 ],
       [0.17924908, 0.34564108, 0.1932234 , ..., 0.16493385, 0.0472651 ,
        0.561074  ],
       [0.18407351, 0.3368781 , 0.18921447, ..., 0.14602253, 0.06858637,
        0.50902337],
       ...,
       [0.2632675 , 0.3020669 , 0.49509865, ..., 0.23050132, 0.15183772,
        0.9113182 ],
       [0.21388009, 0.30657563, 0.43087065, ..., 0.2659141 , 0.1310542 ,
        0.86740553],
       [0.24579468, 0.31356287, 0.44443372, ..., 0.20072085, 0.12147035,
        0.80175203]], dtype=float32)

### Features flow

In [55]:
print("features_flow", video_mine['features_flow'][...].shape)
video_mine['features_flow'][...]

features_flow (283, 1024)


array([[0.0115138 , 0.        , 0.12933995, ..., 0.00129353, 0.00615712,
        0.        ],
       [0.01157713, 0.        , 0.13019228, ..., 0.0013805 , 0.00610533,
        0.        ],
       [0.01149879, 0.        , 0.13028009, ..., 0.00124118, 0.00627848,
        0.        ],
       ...,
       [0.0091691 , 0.        , 0.12460518, ..., 0.00336149, 0.01239737,
        0.        ],
       [0.00966319, 0.        , 0.12442447, ..., 0.00092945, 0.0142435 ,
        0.        ],
       [0.01009411, 0.        , 0.1239302 , ..., 0.        , 0.01236408,
        0.        ]], dtype=float32)

### Features 3D

In [56]:
print("features_3D", video_mine['features_3D'][...].shape)
video_mine['features_3D'][...]

features_3D (284, 2048)


array([[1.4449841 , 0.91934365, 1.1335695 , ..., 0.9544913 , 1.4337465 ,
        1.0540687 ],
       [1.4518617 , 0.86280346, 1.1453713 , ..., 0.9640655 , 1.4517524 ,
        1.0513854 ],
       [1.4863755 , 0.954107  , 1.1712769 , ..., 0.9775462 , 1.484416  ,
        1.0180132 ],
       ...,
       [1.788697  , 1.0815034 , 1.3588432 , ..., 1.2724972 , 1.060129  ,
        0.8041994 ],
       [1.7182093 , 0.9637469 , 1.2734638 , ..., 1.2688835 , 1.1332316 ,
        0.8860217 ],
       [1.6690913 , 1.020613  , 1.2163559 , ..., 1.2730529 , 1.2078943 ,
        0.8786451 ]], dtype=float32)

In [40]:
import numpy as np

SumMe: video name is stored in video_i/video_name.
TVSum: video1-50 corresponds to the same order in ydata-tvsum50.mat, which is the original matlab file provided by TVSum.

In [41]:
path_data = "/data/shuaman/video_summarization/datasets/raw_datasets/SumMe/GT/Air_Force_One.mat"

In [42]:
mat = scipy.io.loadmat(path_data) 

In [43]:
#SumMe
mat.keys()

dict_keys(['__header__', '__version__', '__globals__', 'all_userIDs', 'segments', 'nFrames', 'video_duration', 'FPS', 'gt_score', 'user_score'])

In [44]:
mat["FPS"]

array([[25]], dtype=uint8)

In [45]:
mat["FPS"]

array([[25]], dtype=uint8)

In [46]:
mat["video_duration"]

array([[179.772]])

In [47]:
mat["gt_score"].max()

0.8666666666666667

In [76]:
mat["gt_score"].min()

0.0

In [101]:
mat["gt_score"]

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [105]:
#the averaged score

mat["gt_score"].squeeze()

array([0., 0., 0., ..., 0., 0., 0.])

In [102]:
mat['segments'].shape

(15,)

In [117]:
np.where(mat["user_score"]>0,1,0).max()

1

In [118]:
mat["user_score"].max()

1

In [115]:
mat["user_score"] = np.where(mat["user_score"]>0,1,0)

In [116]:
mat["user_score"].shape

(4494, 15)

In [120]:
mat["gt_score"].shape

(4494, 1)

In [121]:
np.all(np.mean(np.where(mat["user_score"]>0,1,0), axis=1)==mat["gt_score"].squeeze())

True

In [122]:
np.all(np.mean(mat["user_score"], axis=1)==mat["gt_score"].squeeze())

True

In [73]:
mat["user_score"][:,14].shape

(4494,)

In [72]:
np.mean(mat["user_score"], axis=1).max()

2.933333333333333

In [52]:
goundt = mat["user_score"].T

In [53]:
goundt.shape

(15, 4494)

In [56]:
np.mean(goundt[:, ::15], axis=0).shape

(300,)

In [661]:
((goundt - 0)/4).max()

2.75

In [662]:
np.mean(goundt[:,::15], axis=0).max()

2.933333333333333

In [663]:
xd = np.mean(goundt[:,::15], axis=0)

In [664]:
((xd - xd.min()) / (xd.max()-xd.min())).max()


1.0

In [665]:
mat["nFrames"]

array([[4494]], dtype=uint16)

In [666]:
mat['segments'].shape

(1, 15)

In [667]:
# user_score = user_summary

In [40]:
# nFrames = n_frames

In [73]:
la = [1,2,3,4]

In [71]:
lb = ["a","v","c","d"]

In [81]:
enumerate((la, lb))

In [84]:
for idx, a_b in enumerate(zip(la, lb)):
    print(idx, a_b)

0 (1, 'a')
1 (2, 'v')
2 (3, 'c')
3 (4, 'd')


In [ ]:
a = np.array([[1, 0],
                 []
              [0, 1]])