In [1]:
!pip3 freeze | wc -l

80


In [2]:
import pandas as pd

In [3]:
path_info = "/data/shuaman/video_summarization/datasets/raw_datasets/TVsum/ydata-tvsum50-v1_1/data/ydata-tvsum50-info.tsv"
path_ant = "/data/shuaman/video_summarization/datasets/raw_datasets/TVsum/ydata-tvsum50-v1_1/data/ydata-tvsum50-anno.tsv"

In [4]:
df_ant = pd.read_csv(path_ant, sep='\t', names=["video_id", "category", "score"])

In [5]:
df_ant.shape

(1000, 3)

In [6]:
df_ant.head(5)

video_id category                                              score
0  AwmHb44_ouw       VT  4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,...
1  AwmHb44_ouw       VT  2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,...
2  AwmHb44_ouw       VT  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,...
3  AwmHb44_ouw       VT  4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,...
4  AwmHb44_ouw       VT  2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,...

In [7]:
df_info = pd.read_csv(path_info, sep='\t')

In [8]:
df_info.shape

(50, 5)

In [9]:
df_info.head(5)

category     video_id                                              title  \
0       VT  AwmHb44_ouw  #1306 How to change tires for off road vehicle...   
1       VT  98MoyGZKHXc        How to use a tyre repair kit - Which? guide   
2       VT  J0nA4VgnoCo                                   #0001: FLAT TIRE   
3       VT  gzDbaEs1Rlg                 ŠKODA Tips How to Repair Your Tyre   
4       VT  XzYM3PfTM4w                     When to Replace Your Tires GMC   

                                           url length  
0  https://www.youtube.com/watch?v=AwmHb44_ouw   5:54  
1  https://www.youtube.com/watch?v=98MoyGZKHXc   3:07  
2  https://www.youtube.com/watch?v=J0nA4VgnoCo   9:44  
3  https://www.youtube.com/watch?v=gzDbaEs1Rlg   4:48  
4  https://www.youtube.com/watch?v=XzYM3PfTM4w   1:51

In [10]:
import h5py

In [11]:
import scipy.io

In [12]:
# path_just_generated = "/home/shuaman/video_sm/video_summarization/src/eccv16_dataset_tvsum_google_pool5.h5"
path_just_generated = "/home/shuaman/video_sm/video_summarization/src/dataset_tvsum_processed.h5"

In [13]:
#Air_Force_One_data = h5py.File(path_just_generated, 'r')['video_1']
data_all_tvsum_mine = h5py.File(path_just_generated, 'r')

In [14]:
#path_data_preprocessd = "/data/shuaman/video_summarization/datasets/dsnet/datasets/eccv16_dataset_summe_google_pool5.h5"
path_data_preprocessd = "/data/shuaman/video_summarization/datasets/object_features/eccv16_dataset_tvsum_google_pool5.h5"

In [15]:
data_all_tvsum = h5py.File(path_data_preprocessd, 'r')

In [16]:
for i in range(0,50):
    video_gt = data_all_tvsum["video_" + str(i+1)]
    video_mine = data_all_tvsum_mine["video_" + str(i+1)]
    
    perfect = True
    
    print(f'video {i+1} comparison')
    if video_gt['features'][...].shape != video_mine['features'][...].shape:
        perfect = False
        print("features gt", video_gt['features'][...].shape)
        print("features mine", video_mine['features'][...].shape)
        print()
        
    if video_gt['gtscore'][...].shape != video_mine['gtscore'][...].shape:
        perfect = False
        print("gtscore gt", video_gt['gtscore'][...].shape)
        print("gtscore mine", video_mine['gtscore'][...].shape)
        print()
        
#     print("video name gt", video_gt['video_name'][...])
    print("video name mine", video_mine['video_name'][...])
    
    if video_gt['user_summary'][...].shape != video_mine['user_summary'][...].shape:
        perfect = False
        print("user summary gt", video_gt['user_summary'][...].shape)
        print("user summary mine", video_mine['user_summary'][...].shape)
        print()
        
    if video_gt['n_frames'][...] != video_mine['n_frames'][...]:
        perfect = False
        print("n frames gt", video_gt['n_frames'][...])
        print("n frames mine", video_mine['n_frames'][...])
        print()
    if video_gt['change_points'][...].shape != video_mine['change_points'][...].shape:  
        perfect = False
        print("change points gt", video_gt['change_points'][...].shape)
        print("change points mine", video_mine['change_points'][...].shape)
        print()
        
    if video_gt['n_frame_per_seg'][...].shape != video_mine['n_frame_per_seg'][...].shape: 
        perfect = False
        print("n frame per seg gt", video_gt['n_frame_per_seg'][...].shape)
        print("n frame per seg mine", video_mine['n_frame_per_seg'][...].shape)
        print()
    
    if video_gt['picks'][...].shape != video_mine['picks'][...].shape:
        perfect = False
        print("picks gt", video_gt['picks'][...].shape)
        print("picks mine", video_mine['picks'][...].shape)
        print()
        
    if video_gt['n_steps'][...] != video_mine['n_steps'][...]:
        perfect = False
        print("n steps gt", video_gt['n_steps'][...])
        print("n steps mine", video_mine['n_steps'][...])
        
    if perfect: 
        print("Everything is perfect")
        print()

video 1 comparison
video name mine b'AwmHb44_ouw'
Everything is perfect

video 2 comparison
video name mine b'98MoyGZKHXc'
Everything is perfect

video 3 comparison
video name mine b'J0nA4VgnoCo'
Everything is perfect

video 4 comparison
video name mine b'gzDbaEs1Rlg'
Everything is perfect

video 5 comparison
video name mine b'XzYM3PfTM4w'
Everything is perfect

video 6 comparison
video name mine b'HT5vyqe0Xaw'
Everything is perfect

video 7 comparison
video name mine b'sTEELN-vY30'
Everything is perfect

video 8 comparison
video name mine b'vdmoEJ5YbrQ'
Everything is perfect

video 9 comparison
video name mine b'xwqBXPGE9pQ'
Everything is perfect

video 10 comparison
video name mine b'akI8YFjEmUw'
Everything is perfect

video 11 comparison
video name mine b'i3wAGJaaktw'
Everything is perfect

video 12 comparison
video name mine b'Bhxk-O1Y7Ho'
Everything is perfect

video 13 comparison
video name mine b'0tmA_C6XwfM'
Everything is perfect

video 14 comparison
video name mine b'3eYKfiOEJ

# Evaluating a random video

In [17]:
#video 1
i = 49
video_gt = data_all_tvsum["video_" + str(i+1)]
video_mine = data_all_tvsum_mine["video_" + str(i+1)]

### Nombre

In [18]:
# print("video name gt", video_gt['video_name'][...])
print("video name mine", video_mine['video_name'][...])
print()


video name mine b'-esJrBWj2d8'



### Features

In [19]:
print("features gt", video_gt['features'][...].shape)
video_gt['features'][...]

features gt (461, 1024)


array([[0.01285232, 0.00488994, 0.04408618, ..., 0.        , 0.00697408,
        0.00288286],
       [0.02696492, 0.00210219, 0.03573826, ..., 0.        , 0.03454432,
        0.03622464],
       [0.03760021, 0.00563098, 0.02105253, ..., 0.        , 0.0626611 ,
        0.04046915],
       ...,
       [0.00503324, 0.00791355, 0.01199674, ..., 0.0537166 , 0.        ,
        0.        ],
       [0.00829969, 0.00368446, 0.00224579, ..., 0.        , 0.        ,
        0.        ],
       [0.0090147 , 0.00311135, 0.01036933, ..., 0.01561159, 0.        ,
        0.        ]], dtype=float32)

In [20]:
print("features mine", video_mine['features'][...].shape)
video_mine['features'][...]

features mine (461, 1024)


array([[0.13085064, 0.60873055, 0.06406087, ..., 0.22821002, 0.08300549,
        0.10198153],
       [0.07641925, 0.50116944, 0.17399107, ..., 0.14351621, 0.18004933,
        0.1639709 ],
       [0.10422586, 0.6885829 , 0.11321306, ..., 0.15749964, 0.13512695,
        0.15454163],
       ...,
       [1.2246431 , 0.36337605, 0.13238919, ..., 0.35105696, 0.10140699,
        0.06510092],
       [0.9280688 , 0.4847278 , 0.16260758, ..., 0.13488597, 0.05993122,
        0.18613036],
       [0.8867561 , 0.5061773 , 0.11004424, ..., 0.46669558, 0.0886733 ,
        0.28357637]], dtype=float32)

### GTScore

In [21]:
print("gtscore gt", video_gt['gtscore'][...].shape)
video_gt['gtscore'][...]

gtscore gt (461,)


array([0.2375, 0.2375, 0.2375, 0.2375, 0.2375, 0.25  , 0.25  , 0.25  ,
       0.25  , 0.35  , 0.35  , 0.35  , 0.35  , 0.2125, 0.2125, 0.2125,
       0.2125, 0.2   , 0.2   , 0.2   , 0.2   , 0.1   , 0.1   , 0.1   ,
       0.1   , 0.1125, 0.1125, 0.1125, 0.1125, 0.275 , 0.275 , 0.275 ,
       0.275 , 0.275 , 0.275 , 0.275 , 0.275 , 0.3875, 0.3875, 0.3875,
       0.3875, 0.2   , 0.2   , 0.2   , 0.2   , 0.2   , 0.2   , 0.2   ,
       0.2   , 0.225 , 0.225 , 0.225 , 0.225 , 0.2625, 0.2625, 0.2625,
       0.2625, 0.1   , 0.1   , 0.1   , 0.1   , 0.1625, 0.1625, 0.1625,
       0.1625, 0.225 , 0.225 , 0.225 , 0.225 , 0.25  , 0.25  , 0.25  ,
       0.25  , 0.3125, 0.3125, 0.3125, 0.3125, 0.2875, 0.2875, 0.2875,
       0.2875, 0.2625, 0.2625, 0.2625, 0.2625, 0.45  , 0.45  , 0.45  ,
       0.45  , 0.4875, 0.4875, 0.4875, 0.4875, 0.375 , 0.375 , 0.375 ,
       0.375 , 0.5   , 0.5   , 0.5   , 0.5   , 0.425 , 0.425 , 0.425 ,
       0.425 , 0.3875, 0.3875, 0.3875, 0.3875, 0.35  , 0.35  , 0.35  ,
      

In [22]:
print("gtscore mine", video_mine['gtscore'][...].shape)
video_mine['gtscore'][...]

gtscore mine (461,)


array([0.55, 0.55, 0.55, 0.55, 0.55, 0.55, 0.55, 0.55, 0.55, 0.6 , 0.6 ,
       0.6 , 0.6 , 0.5 , 0.5 , 0.5 , 0.5 , 0.45, 0.45, 0.45, 0.45, 0.3 ,
       0.3 , 0.3 , 0.3 , 0.35, 0.35, 0.35, 0.35, 0.5 , 0.5 , 0.5 , 0.5 ,
       0.55, 0.55, 0.55, 0.55, 0.6 , 0.6 , 0.6 , 0.6 , 0.4 , 0.4 , 0.4 ,
       0.4 , 0.4 , 0.4 , 0.4 , 0.4 , 0.45, 0.45, 0.45, 0.45, 0.5 , 0.5 ,
       0.5 , 0.5 , 0.3 , 0.3 , 0.3 , 0.3 , 0.45, 0.45, 0.45, 0.45, 0.7 ,
       0.7 , 0.7 , 0.7 , 0.75, 0.75, 0.75, 0.75, 0.85, 0.85, 0.85, 0.85,
       0.8 , 0.8 , 0.8 , 0.8 , 0.75, 0.75, 0.75, 0.75, 0.8 , 0.8 , 0.8 ,
       0.8 , 0.75, 0.75, 0.75, 0.75, 0.7 , 0.7 , 0.7 , 0.7 , 0.75, 0.75,
       0.75, 0.75, 0.9 , 0.9 , 0.9 , 0.9 , 0.85, 0.85, 0.85, 0.85, 0.85,
       0.85, 0.85, 0.85, 0.9 , 0.9 , 0.9 , 0.9 , 0.8 , 0.8 , 0.8 , 0.8 ,
       0.75, 0.75, 0.75, 0.75, 0.9 , 0.9 , 0.9 , 0.9 , 0.9 , 0.9 , 0.9 ,
       0.9 , 0.85, 0.85, 0.85, 0.85, 0.8 , 0.8 , 0.8 , 0.8 , 0.8 , 0.8 ,
       0.8 , 0.8 , 0.8 , 0.8 , 0.8 , 0.8 , 0.75, 0.

### User summary

In [23]:
print("user summary gt", video_gt['user_summary'][...].shape)
video_gt['user_summary'][...]

user summary gt (20, 6912)


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [24]:
print("user summary mine", video_mine['user_summary'][...].shape)
video_mine['user_summary'][...]

user summary mine (20, 6912)


array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 1., 1., 1.],
       [1., 1., 1., ..., 0., 0., 0.]], dtype=float32)

In [25]:
xd = [5,10,12,15]

In [27]:
# np.hstack((0, xd, 20))

### N frames

In [28]:
print("n frames gt", video_gt['n_frames'][...])

n frames gt 6912


In [29]:
print("n frames mine", video_mine['n_frames'][...])

n frames mine 6912


### Change points

In [30]:
print("change points gt", video_gt['change_points'][...].shape)
video_gt['change_points'][...]

change points gt (47, 2)


array([[   0,  304],
       [ 305,  406],
       [ 407,  539],
       [ 540,  591],
       [ 592,  804],
       [ 805,  834],
       [ 835,  906],
       [ 907,  968],
       [ 969, 1064],
       [1065, 1269],
       [1270, 1516],
       [1517, 1611],
       [1612, 1750],
       [1751, 1934],
       [1935, 2001],
       [2002, 2259],
       [2260, 2365],
       [2366, 2610],
       [2611, 2994],
       [2995, 3126],
       [3127, 3259],
       [3260, 3452],
       [3453, 3597],
       [3598, 3668],
       [3669, 3750],
       [3751, 3851],
       [3852, 4119],
       [4120, 4172],
       [4173, 4293],
       [4294, 4430],
       [4431, 4598],
       [4599, 4675],
       [4676, 4791],
       [4792, 4890],
       [4891, 5030],
       [5031, 5119],
       [5120, 5174],
       [5175, 5333],
       [5334, 5367],
       [5368, 5794],
       [5795, 6005],
       [6006, 6442],
       [6443, 6481],
       [6482, 6583],
       [6584, 6647],
       [6648, 6744],
       [6745, 6911]])

In [31]:


print("change points mine", video_mine['change_points'][...].shape)
video_mine['change_points'][...]

change points mine (47, 2)


array([[   0,  119],
       [ 120,  179],
       [ 180,  269],
       [ 270,  419],
       [ 420,  539],
       [ 540,  599],
       [ 600,  809],
       [ 810,  839],
       [ 840,  899],
       [ 900,  974],
       [ 975, 1274],
       [1275, 1529],
       [1530, 1619],
       [1620, 1754],
       [1755, 1934],
       [1935, 2009],
       [2010, 2369],
       [2370, 2444],
       [2445, 2639],
       [2640, 2999],
       [3000, 3269],
       [3270, 3464],
       [3465, 3599],
       [3600, 3674],
       [3675, 3719],
       [3720, 3809],
       [3810, 3854],
       [3855, 4004],
       [4005, 4049],
       [4050, 4139],
       [4140, 4319],
       [4320, 4439],
       [4440, 4619],
       [4620, 4679],
       [4680, 4799],
       [4800, 4904],
       [4905, 5129],
       [5130, 5309],
       [5310, 5384],
       [5385, 5804],
       [5805, 5969],
       [5970, 6014],
       [6015, 6449],
       [6450, 6494],
       [6495, 6614],
       [6615, 6749],
       [6750, 6911]])

### N frames por segmenot

In [32]:
print("n frame per seg gt", video_gt['n_frame_per_seg'][...].shape)
video_gt['n_frame_per_seg'][...]

n frame per seg gt (47,)


array([305, 102, 133,  52, 213,  30,  72,  62,  96, 205, 247,  95, 139,
       184,  67, 258, 106, 245, 384, 132, 133, 193, 145,  71,  82, 101,
       268,  53, 121, 137, 168,  77, 116,  99, 140,  89,  55, 159,  34,
       427, 211, 437,  39, 102,  64,  97, 167])

In [33]:
video_gt['n_frame_per_seg'][...].mean()

147.06382978723406

In [34]:
print("n frame per seg mine", video_mine['n_frame_per_seg'][...].shape)
video_mine['n_frame_per_seg'][...]

n frame per seg mine (47,)


array([120,  60,  90, 150, 120,  60, 210,  30,  60,  75, 300, 255,  90,
       135, 180,  75, 360,  75, 195, 360, 270, 195, 135,  75,  45,  90,
        45, 150,  45,  90, 180, 120, 180,  60, 120, 105, 225, 180,  75,
       420, 165,  45, 435,  45, 120, 135, 162])

### Picks

In [35]:
print("picks gt", video_gt['picks'][...].shape)
video_gt['picks'][...]

picks gt (461,)


array([   0,   15,   30,   45,   60,   75,   90,  105,  120,  135,  150,
        165,  180,  195,  210,  225,  240,  255,  270,  285,  300,  315,
        330,  345,  360,  375,  390,  405,  420,  435,  450,  465,  480,
        495,  510,  525,  540,  555,  570,  585,  600,  615,  630,  645,
        660,  675,  690,  705,  720,  735,  750,  765,  780,  795,  810,
        825,  840,  855,  870,  885,  900,  915,  930,  945,  960,  975,
        990, 1005, 1020, 1035, 1050, 1065, 1080, 1095, 1110, 1125, 1140,
       1155, 1170, 1185, 1200, 1215, 1230, 1245, 1260, 1275, 1290, 1305,
       1320, 1335, 1350, 1365, 1380, 1395, 1410, 1425, 1440, 1455, 1470,
       1485, 1500, 1515, 1530, 1545, 1560, 1575, 1590, 1605, 1620, 1635,
       1650, 1665, 1680, 1695, 1710, 1725, 1740, 1755, 1770, 1785, 1800,
       1815, 1830, 1845, 1860, 1875, 1890, 1905, 1920, 1935, 1950, 1965,
       1980, 1995, 2010, 2025, 2040, 2055, 2070, 2085, 2100, 2115, 2130,
       2145, 2160, 2175, 2190, 2205, 2220, 2235, 22

In [36]:
print("picks mine", video_mine['picks'][...].shape)
video_mine['picks'][...]

picks mine (461,)


array([   0,   15,   30,   45,   60,   75,   90,  105,  120,  135,  150,
        165,  180,  195,  210,  225,  240,  255,  270,  285,  300,  315,
        330,  345,  360,  375,  390,  405,  420,  435,  450,  465,  480,
        495,  510,  525,  540,  555,  570,  585,  600,  615,  630,  645,
        660,  675,  690,  705,  720,  735,  750,  765,  780,  795,  810,
        825,  840,  855,  870,  885,  900,  915,  930,  945,  960,  975,
        990, 1005, 1020, 1035, 1050, 1065, 1080, 1095, 1110, 1125, 1140,
       1155, 1170, 1185, 1200, 1215, 1230, 1245, 1260, 1275, 1290, 1305,
       1320, 1335, 1350, 1365, 1380, 1395, 1410, 1425, 1440, 1455, 1470,
       1485, 1500, 1515, 1530, 1545, 1560, 1575, 1590, 1605, 1620, 1635,
       1650, 1665, 1680, 1695, 1710, 1725, 1740, 1755, 1770, 1785, 1800,
       1815, 1830, 1845, 1860, 1875, 1890, 1905, 1920, 1935, 1950, 1965,
       1980, 1995, 2010, 2025, 2040, 2055, 2070, 2085, 2100, 2115, 2130,
       2145, 2160, 2175, 2190, 2205, 2220, 2235, 22

### Steps

In [37]:
print("n steps gt", video_gt['n_steps'][...])
video_gt['n_steps'][...]

n steps gt 461


array(461)

In [38]:
print("n steps mine", video_mine['n_steps'][...])
video_mine['n_steps'][...]

n steps mine 461


array(461)

### Features rn

In [39]:
print("features_rn", video_mine['features_rn'][...].shape)
video_mine['features_rn'][...]

features_rn (461, 2048)


array([[0.87798846, 0.22199322, 0.55177367, ..., 0.31372505, 0.43906105,
        0.65014255],
       [0.9314491 , 0.21080258, 0.6839014 , ..., 0.13023528, 0.03431432,
        0.7315979 ],
       [0.64173263, 0.16436134, 0.6298357 , ..., 0.26557612, 0.01073799,
        0.6683708 ],
       ...,
       [0.8821565 , 0.34333536, 0.2969471 , ..., 0.04182025, 0.17499894,
        0.2992565 ],
       [0.80012155, 0.37181324, 0.0958932 , ..., 0.04103221, 0.31764236,
        0.4341777 ],
       [1.0444565 , 0.4723627 , 0.04858677, ..., 0.21349585, 0.19562171,
        0.5905717 ]], dtype=float32)

### Features iv3

In [40]:
print("features_iv3", video_mine['features_iv3'][...].shape)
video_mine['features_iv3'][...]

features_iv3 (461, 2048)


array([[0.61301464, 0.30155516, 0.50708514, ..., 0.4487037 , 0.19814734,
        0.31819656],
       [0.43448606, 0.11932111, 0.38996327, ..., 0.612785  , 0.5186714 ,
        0.3164252 ],
       [0.5204556 , 0.10606392, 0.57971793, ..., 0.5242026 , 0.39393207,
        0.23739387],
       ...,
       [0.08150798, 0.3429116 , 0.1767145 , ..., 0.5381805 , 0.605054  ,
        0.6422535 ],
       [0.12211886, 0.14735039, 0.20191309, ..., 0.4853199 , 0.3078195 ,
        0.6518928 ],
       [0.12104721, 0.12737635, 0.22601843, ..., 0.317763  , 0.2029368 ,
        0.31154668]], dtype=float32)

### Features RGB

In [41]:
print("features_rgb", video_mine['features_rgb'][...].shape)
video_mine['features_rgb'][...]

features_rgb (445, 1024)


array([[0.23402876, 0.21374507, 0.39551735, ..., 0.30458966, 0.0807713 ,
        0.27116126],
       [0.26839814, 0.3402351 , 0.4670905 , ..., 0.28692707, 0.03042341,
        0.26434436],
       [0.20560595, 0.29681405, 0.39957196, ..., 0.21474776, 0.05739497,
        0.23012652],
       ...,
       [0.03722261, 0.7759331 , 0.07860638, ..., 0.6040825 , 0.0568152 ,
        0.21517739],
       [0.11172504, 0.7819399 , 0.18716133, ..., 0.47377235, 0.0528559 ,
        0.21992624],
       [0.0640984 , 0.9512487 , 0.09873799, ..., 0.42324436, 0.08293297,
        0.17310448]], dtype=float32)

### Features flow

In [42]:
print("features_flow", video_mine['features_flow'][...].shape)
video_mine['features_flow'][...]

features_flow (444, 1024)


array([[0.02302182, 0.        , 0.18741386, ..., 0.00407231, 0.05224702,
        0.        ],
       [0.0170913 , 0.        , 0.18599677, ..., 0.00914398, 0.06138529,
        0.        ],
       [0.01772095, 0.        , 0.18002847, ..., 0.00118027, 0.06716105,
        0.        ],
       ...,
       [0.02005116, 0.        , 0.13682742, ..., 0.01545963, 0.15975195,
        0.01391683],
       [0.01762183, 0.        , 0.14329757, ..., 0.        , 0.18505754,
        0.0030712 ],
       [0.02251031, 0.        , 0.12631072, ..., 0.        , 0.21212408,
        0.00259195]], dtype=float32)

### Features 3D

In [43]:
print("features_3D", video_mine['features_3D'][...].shape)
video_mine['features_3D'][...]

features_3D (445, 2048)


array([[2.33934410e-02, 6.04046345e-01, 1.33911669e-01, ...,
        1.37832150e-01, 2.49313310e-01, 2.60762542e-01],
       [1.21976502e-01, 7.27870226e-01, 1.07403815e-01, ...,
        9.01327729e-02, 4.12911385e-01, 1.04337260e-01],
       [2.07496986e-01, 7.85300016e-01, 1.22035183e-01, ...,
        9.35364366e-02, 4.35545802e-01, 7.82976747e-02],
       ...,
       [5.42541027e-01, 1.69420049e-01, 2.87856702e-02, ...,
        3.79524082e-01, 6.14455529e-02, 4.29075547e-02],
       [3.97866368e-01, 1.83645695e-01, 1.37923975e-02, ...,
        4.84709322e-01, 8.70130509e-02, 1.77490860e-02],
       [3.92477572e-01, 1.53314516e-01, 5.06889522e-02, ...,
        5.02738655e-01, 9.93559510e-02, 2.31915707e-04]], dtype=float32)

SumMe: video name is stored in video_i/video_name.
TVSum: video1-50 corresponds to the same order in ydata-tvsum50.mat, which is the original matlab file provided by TVSum.

In [37]:
import numpy as np

In [38]:
path_data = "/data/shuaman/video_summarization/datasets/raw_datasets/TvSum/ydata-tvsum50-v1_1/matlab/ydata-tvsum50.mat"

In [39]:
import os

In [40]:
os.path.basename(path_data)

'ydata-tvsum50.mat'

In [41]:
"/".join(path_data.split("/")[:-1])

'/data/shuaman/video_summarization/datasets/raw_datasets/TvSum/ydata-tvsum50-v1_1/matlab'

In [42]:
!pip3 freeze | wc -l

48


In [44]:
all_mat = h5py.File(path_data,'r')

ERROR! Session/line number was not unique in database. History logging moved to new session 242


In [40]:
all_mat.close()

In [220]:
all_mat

<HDF5 file "ydata-tvsum50.mat" (mode r+)>

In [221]:
list(all_mat.keys())

['#refs#', 'tvsum50']

In [301]:
list(all_mat['tvsum50'].keys())

['category', 'gt_score', 'length', 'nframes', 'title', 'user_anno', 'video']

In [303]:
xdxddd = ['category', 'gt_score', 'length', 'nframes', 'title', 'user_anno', 'video']

In [304]:
xdxddd.index('video')

6

In [302]:
list(all_mat['tvsum50'].keys()).index('nframes')

3

In [265]:
len(all_mat['tvsum50'])

7

In [264]:
len(all_mat['tvsum50']['video'])

50

In [224]:
all_mat['tvsum50']['title']

<HDF5 dataset "title": shape (50, 1), type "|O">

In [225]:
all_mat['tvsum50']['title'][0][0]

<HDF5 object reference>

In [305]:
xd = all_mat['tvsum50']['user_anno'][0][0]

In [307]:
np.array(all_mat[xd]).T.T.shape

(20, 10597)

In [299]:
np.mean(np.array(all_mat[xd])[:,::15], axis=0).shape

(707,)

In [286]:
np.array(all_mat[xd]).shape

(1, 10597)

In [285]:
np.array(all_mat[xd])

array([[2.9, 2.9, 2.9, ..., 1.3, 1.3, 1.3]])

In [ ]:
['a','b'].join

In [253]:
def array_to_id(number_array):
    number_array = number_array.squeeze()
    chr_array = [chr(x) for x in number_array] 
    string_array = ''.join(chr_array)
    
    return string_array

In [254]:
array_to_id(np.array(all_mat[xd]))

'AwmHb44_ouw'

In [50]:
mat = all_mat['video_1']

KeyError: "Unable to open object (object 'video_1' doesn't exist)"

In [654]:
mat["FPS"]

array([[25]], dtype=uint8)

In [655]:
mat["FPS"]

array([[25]], dtype=uint8)

In [656]:
mat["video_duration"]

array([[179.772]])

In [657]:
#the averaged score
mat["gt_score"][:20]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [658]:
mat["user_score"][:,].shape

(4494, 15)

In [659]:
goundt = mat["user_score"].T

In [660]:
goundt.shape

(15, 4494)

In [661]:
((goundt - 0)/4).max()

2.75

In [662]:
np.mean(goundt[:,::15], axis=0).max()

2.933333333333333

In [663]:
xd = np.mean(goundt[:,::15], axis=0)

In [664]:
((xd - xd.min()) / (xd.max()-xd.min())).max()


1.0

In [665]:
mat["nFrames"]

array([[4494]], dtype=uint16)

In [666]:
mat['segments'].shape

(1, 15)

In [667]:
# user_score = user_summary

In [40]:
# nFrames = n_frames

In [73]:
la = [1,2,3,4]

In [71]:
lb = ["a","v","c","d"]

In [81]:
enumerate((la, lb))

In [84]:
for idx, a_b in enumerate(zip(la, lb)):
    print(idx, a_b)

0 (1, 'a')
1 (2, 'v')
2 (3, 'c')
3 (4, 'd')


In [ ]:
a = np.array([[1, 0],
                 []
              [0, 1]])