In [1]:
import pandas as pd

In [2]:
import h5py

In [3]:
import scipy.io

In [4]:
# path_just_generated = "/home/shuaman/video_sm/video_summarization/src/eccv16_dataset_ovp_google_pool5.h5"
path_just_generated = "/data/shuaman/video_summarization/datasets/processed_datasets/dataset_ovp_processed.h5"

In [5]:
data_all_ovp_mine = h5py.File(path_just_generated, 'r')

In [6]:
#path_data_preprocessd = "/data/shuaman/video_summarization/datasets/dsnet/datasets/eccv16_dataset_summe_google_pool5.h5"
path_data_preprocessd = "/data/shuaman/video_summarization/datasets/dsnet/datasets/eccv16_dataset_ovp_google_pool5.h5"

# path_data_preprocessd = "/data/shuaman/video_summarization/datasets/VASNet_datasets/datasets/eccv16_dataset_ovp_google_pool5.h5"

In [12]:
data_all_ovp = h5py.File(path_data_preprocessd, 'r')

In [13]:
for i in range(0,50):
    video_gt = data_all_ovp["video_" + str(i+1)]
    video_mine = data_all_ovp_mine["video_" + str(i+1)]
    
    perfect = True
    
    print(f'video {i+1} comparison')
    if video_gt['features'][...].shape != video_mine['features'][...].shape:
        perfect = False
        print("features gt", video_gt['features'][...].shape)
        print("features mine", video_mine['features'][...].shape)
        print()
        
    if video_gt['gtscore'][...].shape != video_mine['gtscore'][...].shape:
        perfect = False
        print("gtscore gt", video_gt['gtscore'][...].shape)
        print("gtscore mine", video_mine['gtscore'][...].shape)
        print()
        
#     print("video name gt", video_gt['video_name'][...])
    print("video name mine", video_mine['video_name'][...])
    
#     if video_gt['user_summary'][...].shape != video_mine['user_summary'][...].shape:
#         perfect = False
#     print("user summary gt", video_gt['user_summary'][...].shape)
    print("user summary mine", video_mine['user_summary'][...].shape)
    print()
        
    if video_gt['n_frames'][...] != video_mine['n_frames'][...]:
        perfect = False
        print("n frames gt", video_gt['n_frames'][...])
        print("n frames mine", video_mine['n_frames'][...])
        print()
    if video_gt['change_points'][...].shape != video_mine['change_points'][...].shape:  
        perfect = False
        print("change points gt", video_gt['change_points'][...].shape)
        print("change points mine", video_mine['change_points'][...].shape)
        print()
        
    if video_gt['n_frame_per_seg'][...].shape != video_mine['n_frame_per_seg'][...].shape: 
        perfect = False
        print("n frame per seg gt", video_gt['n_frame_per_seg'][...].shape)
        print("n frame per seg mine", video_mine['n_frame_per_seg'][...].shape)
        print()
    
    if video_gt['picks'][...].shape != video_mine['picks'][...].shape:
        perfect = False
        print("picks gt", video_gt['picks'][...].shape)
        print("picks mine", video_mine['picks'][...].shape)
        print()
        
#     if video_gt['n_steps'][...] != video_mine['n_steps'][...]:
#         perfect = False
#     print("n steps gt", video_gt['n_steps'][...])
    print("n steps mine", video_mine['n_steps'][...])
        
    if perfect: 
        print("Everything is perfect")
    print()

video 1 comparison
features gt (219, 1024)
features mine (220, 1024)

gtscore gt (219,)
gtscore mine (220,)

video name mine b'v21'
user summary mine (5, 3291)

n frames gt 3284
n frames mine 3291

change points gt (36, 2)
change points mine (22, 2)

n frame per seg gt (36,)
n frame per seg mine (22,)

picks gt (219,)
picks mine (220,)

n steps mine 220

video 2 comparison
features gt (141, 1024)
features mine (142, 1024)

gtscore gt (141,)
gtscore mine (142,)

video name mine b'v22'
user summary mine (5, 2116)

n frames gt 2114
n frames mine 2116

change points gt (5, 2)
change points mine (15, 2)

n frame per seg gt (5,)
n frame per seg mine (15,)

picks gt (141,)
picks mine (142,)

n steps mine 142

video 3 comparison
features gt (117, 1024)
features mine (118, 1024)

gtscore gt (117,)
gtscore mine (118,)

video name mine b'v23'
user summary mine (5, 1759)

n frames gt 1754
n frames mine 1759

change points gt (18, 2)
change points mine (12, 2)

n frame per seg gt (18,)
n frame per 

In [14]:
# data_all_ovp.close()

# Evaluating a random video

In [15]:
len(list(data_all_ovp.keys()))

50

In [16]:
#video 1
i = 5
video_gt = data_all_ovp["video_" + str(i+1)]
video_mine = data_all_ovp_mine["video_" + str(i+1)]

### Nombre

In [17]:
print("video name gt", video_gt['video_name'][...])
print("video name mine", video_mine['video_name'][...])
print()


video name gt b'v26'
video name mine b'v26'



### Features

In [18]:
print("features gt", video_gt['features'][...].shape)
video_gt['features'][...]

features gt (417, 1024)


array([[0.        , 0.00063744, 0.0004239 , ..., 0.        , 0.        ,
        0.00119737],
       [0.        , 0.00017055, 0.00361269, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.00559055, 0.00706795, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.00646132, 0.00604367, 0.00408943, ..., 0.04038517, 0.        ,
        0.        ],
       [0.00095778, 0.00344445, 0.00019028, ..., 0.02632885, 0.        ,
        0.        ],
       [0.00230708, 0.01052201, 0.        , ..., 0.02598344, 0.00062544,
        0.        ]])

In [19]:
print("features mine", video_mine['features'][...].shape)
video_mine['features'][...]

features mine (418, 1024)


array([[0.72340703, 0.        , 0.7195577 , ..., 0.02046127, 0.5676815 ,
        0.05152322],
       [0.47969568, 0.07899202, 0.7742692 , ..., 0.15734763, 0.56180304,
        0.22742522],
       [0.5817164 , 0.10730603, 0.46078554, ..., 0.3456199 , 0.29357395,
        0.36285648],
       ...,
       [0.30914876, 1.6056086 , 0.55164814, ..., 0.06912694, 0.37902352,
        0.13202588],
       [0.22690551, 1.5329564 , 0.5399338 , ..., 0.01661837, 0.24845196,
        0.30952746],
       [0.23797946, 1.1459279 , 0.6015128 , ..., 0.11645585, 0.5221332 ,
        0.41808724]], dtype=float32)

In [28]:
import numpy as np
print(np.all(video_mine['features_rgb'][...]==video_gt['features_rgb'][...]))
print(np.all(video_mine['features_flow'][...]==video_gt['features_flow'][...]))
print(np.all(video_mine['features_rn'][...]==video_gt['features_rn'][...]))
print(np.all(video_mine['features_iv3'][...]==video_gt['features_iv3'][...]))
print(np.all(video_mine['features_3D'][...]==video_gt['features_3D'][...]))

True
True
True
True
True


### GTScore

In [14]:
print("gtscore gt", video_gt['gtscore'][...].shape)
video_gt['gtscore'][...]

gtscore gt (417,)


array([0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1.

In [18]:
video_gt['gtscore'][...].sum()

116.0

In [20]:
import numpy as np

In [21]:
np.where(video_mine['gtscore'][...]>0,1,0).sum()

304

In [15]:
print("gtscore mine", video_mine['gtscore'][...].shape)
video_mine['gtscore'][...]

gtscore mine (418,)


array([0.60000002, 0.60000002, 0.60000002, 0.60000002, 0.60000002,
       0.60000002, 0.60000002, 0.60000002, 0.60000002, 0.60000002,
       0.2       , 0.2       , 0.2       , 0.2       , 0.2       ,
       0.2       , 0.2       , 0.2       , 0.2       , 0.2       ,
       0.2       , 0.2       , 0.2       , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.60000002, 0.60000002, 0.60000002, 0.60000002,
       0.60000002, 0.60000002, 0.60000002, 0.60000002, 0.60000002,
       0.60000002, 0.60000002, 0.60000002, 0.60000002, 0.60000002,
       0.60000002, 0.60000002, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.40000001, 0.40000001, 0.40000001,
       0.40000001, 0.40000001, 0.40000001, 0.2       , 0.2       ,
       0.2       , 0.2       , 0.2       , 0.2       , 0.     

### User summary

In [29]:
print("user summary gt", video_gt['user_summary'][...].shape)
video_gt['user_summary'][...]

user summary gt (5, 6268)


array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)

In [17]:
print("user summary mine", video_mine['user_summary'][...].shape)
video_mine['user_summary'][...]

user summary mine (5, 6268)


array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

### N frames

In [20]:
print("n frames gt", video_gt['n_frames'][...])

n frames gt 6254


In [21]:
print("n frames mine", video_mine['n_frames'][...])

n frames mine 6268


### Change points

In [22]:
print("change points gt", video_gt['change_points'][...].shape)
video_gt['change_points'][...]

change points gt (34, 2)


array([[   0,  149],
       [ 150,  329],
       [ 330,  524],
       [ 525,  854],
       [ 855, 1004],
       [1005, 1259],
       [1260, 1739],
       [1740, 1814],
       [1815, 1934],
       [1935, 2144],
       [2145, 2279],
       [2280, 2459],
       [2460, 2654],
       [2655, 2774],
       [2775, 2909],
       [2910, 3119],
       [3120, 3374],
       [3375, 3524],
       [3525, 3674],
       [3675, 4064],
       [4065, 4274],
       [4275, 4499],
       [4500, 4664],
       [4665, 4784],
       [4785, 4934],
       [4935, 5084],
       [5085, 5159],
       [5160, 5264],
       [5265, 5504],
       [5505, 5639],
       [5640, 5834],
       [5835, 5954],
       [5955, 6119],
       [6120, 6253]])

In [23]:
print("change points mine", video_mine['change_points'][...].shape)
video_mine['change_points'][...]

change points mine (42, 2)


array([[   0,  149],
       [ 150,  344],
       [ 345,  614],
       [ 615,  854],
       [ 855, 1019],
       [1020, 1109],
       [1110, 1274],
       [1275, 1754],
       [1755, 1829],
       [1830, 1949],
       [1950, 2174],
       [2175, 2294],
       [2295, 2474],
       [2475, 2669],
       [2670, 2789],
       [2790, 2924],
       [2925, 3134],
       [3135, 3284],
       [3285, 3389],
       [3390, 3539],
       [3540, 3614],
       [3615, 3689],
       [3690, 3869],
       [3870, 4079],
       [4080, 4169],
       [4170, 4274],
       [4275, 4379],
       [4380, 4499],
       [4500, 4679],
       [4680, 4814],
       [4815, 4949],
       [4950, 5084],
       [5085, 5174],
       [5175, 5279],
       [5280, 5384],
       [5385, 5564],
       [5565, 5654],
       [5655, 5849],
       [5850, 5954],
       [5955, 6059],
       [6060, 6134],
       [6135, 6267]])

### N frames por segmenot

In [24]:
print("n frame per seg gt", video_gt['n_frame_per_seg'][...].shape)
video_gt['n_frame_per_seg'][...]

n frame per seg gt (34,)


array([150, 180, 195, 330, 150, 255, 480,  75, 120, 210, 135, 180, 195,
       120, 135, 210, 255, 150, 150, 390, 210, 225, 165, 120, 150, 150,
        75, 105, 240, 135, 195, 120, 165, 134])

In [25]:
print("n frame per seg mine", video_mine['n_frame_per_seg'][...].shape)
video_mine['n_frame_per_seg'][...]

n frame per seg mine (42,)


array([150, 195, 270, 240, 165,  90, 165, 480,  75, 120, 225, 120, 180,
       195, 120, 135, 210, 150, 105, 150,  75,  75, 180, 210,  90, 105,
       105, 120, 180, 135, 135, 135,  90, 105, 105, 180,  90, 195, 105,
       105,  75, 133])

### Picks

In [26]:
print("picks gt", video_gt['picks'][...].shape)
video_gt['picks'][...]

picks gt (417,)


array([   0,   15,   30,   45,   60,   75,   90,  105,  120,  135,  150,
        165,  180,  195,  210,  225,  240,  255,  270,  285,  300,  315,
        330,  345,  360,  375,  390,  405,  420,  435,  450,  465,  480,
        495,  510,  525,  540,  555,  570,  585,  600,  615,  630,  645,
        660,  675,  690,  705,  720,  735,  750,  765,  780,  795,  810,
        825,  840,  855,  870,  885,  900,  915,  930,  945,  960,  975,
        990, 1005, 1020, 1035, 1050, 1065, 1080, 1095, 1110, 1125, 1140,
       1155, 1170, 1185, 1200, 1215, 1230, 1245, 1260, 1275, 1290, 1305,
       1320, 1335, 1350, 1365, 1380, 1395, 1410, 1425, 1440, 1455, 1470,
       1485, 1500, 1515, 1530, 1545, 1560, 1575, 1590, 1605, 1620, 1635,
       1650, 1665, 1680, 1695, 1710, 1725, 1740, 1755, 1770, 1785, 1800,
       1815, 1830, 1845, 1860, 1875, 1890, 1905, 1920, 1935, 1950, 1965,
       1980, 1995, 2010, 2025, 2040, 2055, 2070, 2085, 2100, 2115, 2130,
       2145, 2160, 2175, 2190, 2205, 2220, 2235, 22

In [27]:
print("picks mine", video_mine['picks'][...].shape)
video_mine['picks'][...]

picks mine (418,)


array([   0,   15,   30,   45,   60,   75,   90,  105,  120,  135,  150,
        165,  180,  195,  210,  225,  240,  255,  270,  285,  300,  315,
        330,  345,  360,  375,  390,  405,  420,  435,  450,  465,  480,
        495,  510,  525,  540,  555,  570,  585,  600,  615,  630,  645,
        660,  675,  690,  705,  720,  735,  750,  765,  780,  795,  810,
        825,  840,  855,  870,  885,  900,  915,  930,  945,  960,  975,
        990, 1005, 1020, 1035, 1050, 1065, 1080, 1095, 1110, 1125, 1140,
       1155, 1170, 1185, 1200, 1215, 1230, 1245, 1260, 1275, 1290, 1305,
       1320, 1335, 1350, 1365, 1380, 1395, 1410, 1425, 1440, 1455, 1470,
       1485, 1500, 1515, 1530, 1545, 1560, 1575, 1590, 1605, 1620, 1635,
       1650, 1665, 1680, 1695, 1710, 1725, 1740, 1755, 1770, 1785, 1800,
       1815, 1830, 1845, 1860, 1875, 1890, 1905, 1920, 1935, 1950, 1965,
       1980, 1995, 2010, 2025, 2040, 2055, 2070, 2085, 2100, 2115, 2130,
       2145, 2160, 2175, 2190, 2205, 2220, 2235, 22

### Steps

In [28]:
# print("n steps gt", video_gt['n_steps'][...])
# video_gt['n_steps'][...]

In [29]:
print("n steps mine", video_mine['n_steps'][...])
video_mine['n_steps'][...]

n steps mine 418


array(418)

### Features rn

In [30]:
print("features_rn", video_mine['features_rn'][...].shape)
video_mine['features_rn'][...]

features_rn (418, 2048)


array([[0.91701084, 0.37103629, 0.18371409, ..., 0.20647991, 0.4169102 ,
        0.21549632],
       [1.25150049, 0.56209326, 0.17832935, ..., 0.08810326, 0.29659665,
        0.25123107],
       [1.7953192 , 0.32618594, 0.04273757, ..., 0.0564817 , 0.75746965,
        0.34218612],
       ...,
       [1.29171288, 0.59979737, 0.77721214, ..., 0.91315055, 1.55076754,
        0.21494585],
       [0.88447505, 0.16722341, 0.42877698, ..., 0.55294901, 1.66218162,
        0.11878984],
       [0.7686429 , 0.22929385, 0.39944509, ..., 0.56337053, 0.97576636,
        0.09575848]])

### Features iv3

In [31]:
print("features_iv3", video_mine['features_iv3'][...].shape)
video_mine['features_iv3'][...]

features_iv3 (418, 2048)


array([[0.36381626, 0.41588911, 0.65189683, ..., 0.29057899, 1.54852009,
        0.12888065],
       [0.45208114, 0.36702779, 0.94460356, ..., 0.14587021, 0.53438622,
        0.02822377],
       [0.35142094, 0.25603133, 1.00757074, ..., 0.22188465, 1.07591128,
        0.00353241],
       ...,
       [0.18119276, 0.09467727, 0.04094694, ..., 0.08011962, 0.26032543,
        0.3326093 ],
       [0.08665416, 0.11277606, 0.04814126, ..., 0.03089454, 0.28368255,
        0.33611947],
       [0.1090709 , 0.15836516, 0.05889504, ..., 0.02179396, 0.1423464 ,
        0.36872318]])

### Features RGB

In [32]:
print("features_rgb", video_mine['features_rgb'][...].shape)
video_mine['features_rgb'][...]

features_rgb (402, 1024)


array([[0.12040778, 0.08924994, 0.25639349, ..., 0.12150455, 0.422279  ,
        0.        ],
       [0.0742717 , 0.10037775, 0.65210903, ..., 0.20349845, 0.26093909,
        0.        ],
       [0.07004884, 0.16937833, 0.32442477, ..., 0.06053451, 0.10074295,
        0.0020523 ],
       ...,
       [0.02957824, 0.28675556, 0.11072949, ..., 0.10791171, 0.18353108,
        0.02141355],
       [0.03091061, 0.24096464, 0.13950953, ..., 0.31590939, 0.09879748,
        0.02429446],
       [0.02267014, 0.44684321, 0.14413515, ..., 0.19736852, 0.08168415,
        0.0130678 ]])

### Features flow

In [33]:
print("features_flow", video_mine['features_flow'][...].shape)
video_mine['features_flow'][...]

features_flow (401, 1024)


array([[0.00350306, 0.        , 0.19425483, ..., 0.        , 0.11394422,
        0.00663556],
       [0.00428692, 0.        , 0.16077322, ..., 0.        , 0.07616258,
        0.02007624],
       [0.00489576, 0.        , 0.14479241, ..., 0.        , 0.09149326,
        0.00890846],
       ...,
       [0.00517061, 0.        , 0.13716257, ..., 0.        , 0.0511636 ,
        0.        ],
       [0.00899672, 0.        , 0.09445009, ..., 0.        , 0.04601432,
        0.        ],
       [0.0077873 , 0.        , 0.08104715, ..., 0.        , 0.04377815,
        0.        ]])

### Features 3D

In [34]:
print("features_3D", video_mine['features_3D'][...].shape)
video_mine['features_3D'][...]

features_3D (402, 2048)


array([[0.01141421, 0.71902668, 0.25896689, ..., 0.1422621 , 0.0861815 ,
        0.00882405],
       [0.02725962, 0.52138793, 0.30773759, ..., 0.25383136, 0.11571796,
        0.00349379],
       [0.02982524, 0.62953007, 0.32884738, ..., 0.30199018, 0.03786028,
        0.0057897 ],
       ...,
       [0.48453256, 0.32303569, 0.09364371, ..., 0.40632352, 0.12540844,
        0.23443155],
       [0.41358986, 0.20823215, 0.05869264, ..., 0.62941879, 0.07164476,
        0.24125667],
       [0.56094712, 0.38486218, 0.05387338, ..., 0.57304704, 0.03873715,
        0.22623166]])

SumMe: video name is stored in video_i/video_name.
TVSum: video1-50 corresponds to the same order in ydata-tvsum50.mat, which is the original matlab file provided by TVSum.

In [ ]:
segmentos de 4.5 seg en promedio

In [27]:
4.5*30

135.0

In [30]:
import numpy as np

In [31]:
import os

In [32]:
import cv2

In [33]:
path_data = "/data/shuaman/video_summarization/datasets/raw_datasets/VSUMM/UserSummary"

In [34]:
name_video = "v21"

In [35]:
path_video = f"/data/shuaman/video_summarization/datasets/raw_datasets/VSUMM/database/{name_video}.mpg"

In [36]:
path_video

'/data/shuaman/video_summarization/datasets/raw_datasets/VSUMM/database/v21.mpg'

In [37]:
video_capture = cv2.VideoCapture(path_video)

In [38]:
fps = video_capture.get(cv2.CAP_PROP_FPS)
fps

29.97002997002997

In [39]:
os.listdir("/data/shuaman/video_summarization/datasets/raw_datasets/VSUMM/database/")

['v60.mpg',
 'v32.mpg',
 'v45.mpg',
 'v36.mpg',
 'v34.mpg',
 'v68.mpg',
 'v28.mpg',
 'v24.mpg',
 'v22.mpg',
 'v58.mpg',
 'v30.mpg',
 'v63.mpg',
 'v52.mpg',
 'v41.mpg',
 'v23.mpg',
 'v69.mpg',
 'v35.mpg',
 'v70.mpg',
 'v59.mpg',
 'v62.mpg',
 'v55.mpg',
 'v48.mpg',
 'v57.mpg',
 'v40.mpg',
 'v29.mpg',
 'v54.mpg',
 'v44.mpg',
 'v38.mpg',
 'v47.mpg',
 'v21.mpg',
 'v33.mpg',
 'v51.mpg',
 'v27.mpg',
 'v65.mpg',
 'v49.mpg',
 'v25.mpg',
 'v56.mpg',
 'v53.mpg',
 'v26.mpg',
 'v61.mpg',
 'v37.mpg',
 'v46.mpg',
 'v67.mpg',
 'v64.mpg',
 'v43.mpg',
 'v39.mpg',
 'v42.mpg',
 'v66.mpg',
 'v50.mpg',
 'v31.mpg']

In [40]:
[gtvideo for gtvideo in os.listdir(path_data) if os.path.isdir(os.path.join(path_data, gtvideo))]

['v65',
 'v51',
 'v43',
 'v22',
 'v58',
 'v45',
 'v32',
 'v50',
 'v61',
 'v27',
 'v29',
 'v54',
 'v63',
 'v36',
 'v37',
 'v57',
 'v41',
 'v44',
 'v30',
 'v56',
 'v38',
 'v42',
 'v70',
 'v33',
 'v52',
 'v55',
 'v64',
 'v31',
 'v21',
 'v24',
 'v62',
 'v59',
 'v40',
 'v26',
 'v69',
 'v66',
 'v25',
 'v35',
 'v60',
 'v28',
 'v53',
 'v68',
 'v48',
 'v23',
 'v49',
 'v39',
 'v34',
 'v47',
 'v67',
 'v46']

In [41]:
user_list = os.listdir(os.path.join(path_data, name_video))

In [42]:
user_list

['user1', 'user3', 'user5', 'user4', 'user2']

In [58]:
user_summary = []
for user_summ in np.sort(user_list):
    print(os.listdir(os.path.join(path_data, name_video, user_summ)))
    print(np.sort([int(frame.split('.')[0][5:]) for frame in os.listdir(os.path.join(path_data, name_video, user_summ))]))
    print()
    list_summ = [int(np.ceil(int(frame.split('.')[0][5:])*5.2)) for frame in os.listdir(os.path.join(path_data, name_video, user_summ))]
    list_summ.sort()
    user_summary.append(list_summ)

['Frame2521.jpeg', 'Frame841.jpeg', 'Frame421.jpeg', 'Frame931.jpeg', 'Frame2731.jpeg', 'Frame121.jpeg', 'Frame1081.jpeg', 'Frame2101.jpeg', 'Frame2041.jpeg', 'Frame721.jpeg', 'Frame301.jpeg']
[ 121  301  421  721  841  931 1081 2041 2101 2521 2731]

['Frame3060.jpeg', 'Frame780.jpeg', 'Frame961.jpeg', 'Frame2101.jpeg', 'Frame301.jpeg']
[ 301  780  961 2101 3060]

['Frame1321.jpeg', 'Frame841.jpeg', 'Frame631.jpeg', 'Frame961.jpeg', 'Frame2101.jpeg', 'Frame2671.jpeg', 'Frame1921.jpeg', 'Frame1771.jpeg', 'Frame2912.jpeg']
[ 631  841  961 1321 1771 1921 2101 2671 2912]

['Frame1350.jpeg', 'Frame1711.jpeg', 'Frame2731.jpeg', 'Frame1591.jpeg', 'Frame871.jpeg', 'Frame2041.jpeg', 'Frame721.jpeg', 'Frame301.jpeg', 'Frame3211.jpeg']
[ 301  721  871 1350 1591 1711 2041 2731 3211]

['Frame2011.jpeg', 'Frame3151.jpeg', 'Frame961.jpeg', 'Frame2101.jpeg', 'Frame571.jpeg']
[ 571  961 2011 2101 3151]



In [59]:
user_summary

[[630, 1566, 2190, 3750, 4374, 4842, 5622, 10614, 10926, 13110, 14202],
 [1566, 4056, 4998, 10926, 15912],
 [3282, 4374, 4998, 6870, 9210, 9990, 10926, 13890, 15143],
 [1566, 3750, 4530, 7020, 8274, 8898, 10614, 14202, 16698],
 [2970, 4998, 10458, 10926, 16386]]

In [49]:
user_summary

[[121, 301, 421, 721, 841, 931, 1081, 2041, 2101, 2521, 2731],
 [301, 780, 961, 2101, 3060],
 [631, 841, 961, 1321, 1771, 1921, 2101, 2671, 2912],
 [301, 721, 871, 1350, 1591, 1711, 2041, 2731, 3211],
 [571, 961, 2011, 2101, 3151]]

In [106]:
cp_dummy = video_gt['change_points'][...]

In [121]:
 new_gt_user = np.zeros(n_frames)

In [158]:
segments = [segment for segment in cp_dummy for frame in user_summary[0] if (frame>=segment[0]) and (frame<=segment[1])]
segments

[array([ 75, 164]),
 array([255, 314]),
 array([360, 629]),
 array([630, 749]),
 array([750, 854]),
 array([855, 944]),
 array([ 945, 1094]),
 array([1980, 2069]),
 array([2070, 2204]),
 array([2460, 2534]),
 array([2715, 2759])]

In [159]:
segments[0][0]

75

In [129]:
new_gt_user[segments[0][0]:segments[0][1]+1] = 1

In [130]:
new_gt_user[627:]

array([1., 1., 1., ..., 0., 0., 0.])

In [107]:
cp_dummy

array([[   0,   74],
       [  75,  164],
       [ 165,  209],
       [ 210,  254],
       [ 255,  314],
       [ 315,  359],
       [ 360,  629],
       [ 630,  749],
       [ 750,  854],
       [ 855,  944],
       [ 945, 1094],
       [1095, 1229],
       [1230, 1379],
       [1380, 1484],
       [1485, 1529],
       [1530, 1604],
       [1605, 1679],
       [1680, 1739],
       [1740, 1844],
       [1845, 1904],
       [1905, 1979],
       [1980, 2069],
       [2070, 2204],
       [2205, 2279],
       [2280, 2369],
       [2370, 2459],
       [2460, 2534],
       [2535, 2639],
       [2640, 2714],
       [2715, 2759],
       [2760, 2834],
       [2835, 2909],
       [2910, 2984],
       [2985, 3044],
       [3045, 3224],
       [3225, 3283]])

In [108]:
n_frames = 3284

In [161]:
gt_video = []
for user in user_summary:
    new_gt_user = np.zeros(n_frames)
    segments = [segment for segment in cp_dummy for frame in user if (frame>=segment[0]) and (frame<=segment[1])]
    for segment in segments:
        new_gt_user[int(segment[0]):int(segment[1]+1)] = 1
    gt_video.append(new_gt_user)

In [166]:
gt_video.shape

AttributeError: 'list' object has no attribute 'shape'

In [171]:
np.array(gt_video).T.T.shape[1]

3284

In [164]:
np.array(gt_video)[0][2745:2770]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [115]:
np.zeros(3284)

array([0., 0., 0., ..., 0., 0., 0.])