In [1]:
import pandas as pd

In [2]:
import h5py

In [3]:
import scipy.io

In [4]:
# path_just_generated = "/home/shuaman/video_sm/video_summarization/src/eccv16_dataset_youtube_google_pool5.h5"
path_just_generated = "/home/shuaman/video_sm/video_summarization/src/dataset_youtube_processed.h5"

In [5]:
data_all_yt_mine = h5py.File(path_just_generated, 'r')

In [6]:
#path_data_preprocessd = "/data/shuaman/video_summarization/datasets/dsnet/datasets/eccv16_dataset_summe_google_pool5.h5"
path_data_preprocessd = "/data/shuaman/video_summarization/datasets/dsnet/datasets/eccv16_dataset_youtube_google_pool5.h5"

In [7]:
data_all_yt = h5py.File(path_data_preprocessd, 'r')

In [8]:
for i in range(0,39):
    if i>10:
        video_gt = data_all_yt["video_" + str(i+12)]
    else:    
        video_gt = data_all_yt["video_" + str(i+11)]
    video_mine = data_all_yt_mine["video_" + str(i+1)]
    
    perfect = True
    
    print(f'video {i+1} comparison')
    if video_gt['features'][...].shape != video_mine['features'][...].shape:
        perfect = False
        print("features gt", video_gt['features'][...].shape)
        print("features mine", video_mine['features'][...].shape)
        print()
        
    if video_gt['gtscore'][...].shape != video_mine['gtscore'][...].shape:
        perfect = False
        print("gtscore gt", video_gt['gtscore'][...].shape)
        print("gtscore mine", video_mine['gtscore'][...].shape)
        print()
        
#     print("video name gt", video_gt['video_name'][...])
    print("video name mine", video_mine['video_name'][...])
    
#     if video_gt['user_summary'][...].shape != video_mine['user_summary'][...].shape:
#         perfect = False
#     print("user summary gt", video_gt['user_summary'][...].shape)
    print("user summary mine", video_mine['user_summary'][...].shape)
    print()
        
    if video_gt['n_frames'][...] != video_mine['n_frames'][...]:
        perfect = False
        print("n frames gt", video_gt['n_frames'][...])
        print("n frames mine", video_mine['n_frames'][...])
        print()
    if video_gt['change_points'][...].shape != video_mine['change_points'][...].shape:  
        perfect = False
        print("change points gt", video_gt['change_points'][...].shape)
        print("change points mine", video_mine['change_points'][...].shape)
        print()
        
    if video_gt['n_frame_per_seg'][...].shape != video_mine['n_frame_per_seg'][...].shape: 
        perfect = False
        print("n frame per seg gt", video_gt['n_frame_per_seg'][...].shape)
        print("n frame per seg mine", video_mine['n_frame_per_seg'][...].shape)
        print()
    
    if video_gt['picks'][...].shape != video_mine['picks'][...].shape:
        perfect = False
        print("picks gt", video_gt['picks'][...].shape)
        print("picks mine", video_mine['picks'][...].shape)
        print()
        
#     if video_gt['n_steps'][...] != video_mine['n_steps'][...]:
#         perfect = False
#     print("n steps gt", video_gt['n_steps'][...])
    print("n steps mine", video_mine['n_steps'][...])
        
    if perfect: 
        print("Everything is perfect")
    print()

video 1 comparison
features gt (548, 1024)
features mine (146, 1024)

gtscore gt (548,)
gtscore mine (146,)

video name mine v100
user summary mine (5, 2180)

n frames gt 8219
n frames mine 2180

change points gt (52, 2)
change points mine (15, 2)

n frame per seg gt (52,)
n frame per seg mine (15,)

picks gt (548,)
picks mine (146,)

n steps mine 146

video 2 comparison
features gt (890, 1024)
features mine (154, 1024)

gtscore gt (890,)
gtscore mine (154,)

video name mine v101
user summary mine (5, 2307)

n frames gt 13349
n frames mine 2307

change points gt (52, 2)
change points mine (16, 2)

n frame per seg gt (52,)
n frame per seg mine (16,)

picks gt (890,)
picks mine (154,)

n steps mine 154

video 3 comparison
features gt (398, 1024)
features mine (356, 1024)

gtscore gt (398,)
gtscore mine (356,)

video name mine v102
user summary mine (5, 5337)

n frames gt 5969
n frames mine 5337

change points gt (62, 2)
change points mine (36, 2)

n frame per seg gt (62,)
n frame per seg

# Evaluating a random video

In [9]:
#video 1
i = 0
video_gt = data_all_yt["video_" + str(i+11)]
video_mine = data_all_yt_mine["video_" + str(i+1)]

### Nombre

In [10]:
# print("video name gt", video_gt['video_name'][...])
print("video name mine", video_mine['video_name'][...])
print()


video name mine v100



### Features

In [11]:
print("features gt", video_gt['features'][...].shape)
video_gt['features'][...]

features gt (548, 1024)


array([[0.00480175, 0.00191541, 0.00144849, ..., 0.00059296, 0.        ,
        0.        ],
       [0.02278749, 0.        , 0.00032969, ..., 0.03141938, 0.        ,
        0.01645034],
       [0.00380519, 0.01080663, 0.01013621, ..., 0.00068079, 0.09338888,
        0.00776942],
       ...,
       [0.00054534, 0.        , 0.02558603, ..., 0.00022958, 0.        ,
        0.        ],
       [0.00093175, 0.        , 0.02311102, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.02216335, ..., 0.        , 0.        ,
        0.        ]])

In [12]:
print("features mine", video_mine['features'][...].shape)
video_mine['features'][...]

features mine (146, 1024)


array([[1.16738141, 0.39022049, 0.22681116, ..., 0.53215802, 0.20395179,
        0.26799294],
       [1.08243549, 0.37534344, 0.29622772, ..., 0.30814251, 0.04402435,
        0.11919551],
       [0.99558741, 0.39815995, 0.34530658, ..., 0.53375638, 0.21224354,
        0.04542959],
       ...,
       [0.99729162, 0.20400564, 0.01791004, ..., 0.13528727, 0.37678674,
        0.        ],
       [1.04785776, 0.24927355, 0.06181312, ..., 0.07754877, 0.28842911,
        0.        ],
       [1.0213958 , 0.26427928, 0.02285194, ..., 0.08637314, 0.38502634,
        0.        ]])

### GTScore

In [13]:
print("gtscore gt", video_gt['gtscore'][...].shape)
video_gt['gtscore'][...]

gtscore gt (548,)


array([0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [14]:
print("gtscore mine", video_mine['gtscore'][...].shape)
video_mine['gtscore'][...]

gtscore mine (146,)


array([1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       0.80000001, 0.80000001, 0.80000001, 0.80000001, 0.80000001,
       0.80000001, 0.80000001, 0.80000001, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.2       ,
       0.2       , 0.2       , 0.2       , 0.2       , 0.2       ,
       0.2       , 0.2       , 0.40000001, 0.40000001, 0.40000001,
       0.40000001, 0.40000001, 0.40000001, 0.40000001, 0.40000001,
       0.40000001, 0.40000001, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.2       , 0.2       ,
       0.2       , 0.2       , 0.2       , 0.2       , 0.2    

### User summary

In [15]:
# print("user summary gt", video_gt['user_summary'][...].shape)
# video_gt['user_summary'][...]

In [16]:
print("user summary mine", video_mine['user_summary'][...].shape)
video_mine['user_summary'][...]

user summary mine (5, 2180)


array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.]])

In [17]:
video_mine['user_summary'][...][0].sum()

750.0

In [18]:
video_mine['user_summary'][...][1].sum()

870.0

In [19]:
video_mine['user_summary'][...][2].sum()

915.0

### N frames

In [20]:
print("n frames gt", video_gt['n_frames'][...])

n frames gt 8219


In [21]:
print("n frames mine", video_mine['n_frames'][...])

n frames mine 2180


### Change points

In [22]:
print("change points gt", video_gt['change_points'][...].shape)
video_gt['change_points'][...]

change points gt (52, 2)


array([[   0,  149],
       [ 150,  239],
       [ 240,  764],
       [ 765,  884],
       [ 885,  959],
       [ 960, 1019],
       [1020, 1229],
       [1230, 1439],
       [1440, 1529],
       [1530, 1769],
       [1770, 1889],
       [1890, 2129],
       [2130, 2219],
       [2220, 2414],
       [2415, 2444],
       [2445, 2579],
       [2580, 2744],
       [2745, 2789],
       [2790, 3179],
       [3180, 3329],
       [3330, 3419],
       [3420, 3614],
       [3615, 3764],
       [3765, 3899],
       [3900, 4109],
       [4110, 4634],
       [4635, 4829],
       [4830, 4934],
       [4935, 5069],
       [5070, 5174],
       [5175, 5279],
       [5280, 5384],
       [5385, 5549],
       [5550, 5684],
       [5685, 5774],
       [5775, 5879],
       [5880, 6029],
       [6030, 6299],
       [6300, 6569],
       [6570, 6749],
       [6750, 6809],
       [6810, 6944],
       [6945, 7034],
       [7035, 7244],
       [7245, 7334],
       [7335, 7544],
       [7545, 7619],
       [7620,

In [23]:
print("change points mine", video_mine['change_points'][...].shape)
video_mine['change_points'][...]

change points mine (15, 2)


array([[   0,  374],
       [ 375,  494],
       [ 495,  554],
       [ 555,  614],
       [ 615,  779],
       [ 780, 1019],
       [1020, 1169],
       [1170, 1289],
       [1290, 1409],
       [1410, 1469],
       [1470, 1529],
       [1530, 1589],
       [1590, 1709],
       [1710, 1814],
       [1815, 2179]])

### N frames por segmenot

In [24]:
print("n frame per seg gt", video_gt['n_frame_per_seg'][...].shape)
video_gt['n_frame_per_seg'][...]

n frame per seg gt (52,)


array([150,  90, 525, 120,  75,  60, 210, 210,  90, 240, 120, 240,  90,
       195,  30, 135, 165,  45, 390, 150,  90, 195, 150, 135, 210, 525,
       195, 105, 135, 105, 105, 105, 165, 135,  90, 105, 150, 270, 270,
       180,  60, 135,  90, 210,  90, 210,  75, 225, 105, 135,  75,  59])

In [25]:
print("n frame per seg mine", video_mine['n_frame_per_seg'][...].shape)
video_mine['n_frame_per_seg'][...]

n frame per seg mine (15,)


array([375, 120,  60,  60, 165, 240, 150, 120, 120,  60,  60,  60, 120,
       105, 365])

### Picks

In [26]:
print("picks gt", video_gt['picks'][...].shape)
video_gt['picks'][...]

picks gt (548,)


array([   0,   15,   30,   45,   60,   75,   90,  105,  120,  135,  150,
        165,  180,  195,  210,  225,  240,  255,  270,  285,  300,  315,
        330,  345,  360,  375,  390,  405,  420,  435,  450,  465,  480,
        495,  510,  525,  540,  555,  570,  585,  600,  615,  630,  645,
        660,  675,  690,  705,  720,  735,  750,  765,  780,  795,  810,
        825,  840,  855,  870,  885,  900,  915,  930,  945,  960,  975,
        990, 1005, 1020, 1035, 1050, 1065, 1080, 1095, 1110, 1125, 1140,
       1155, 1170, 1185, 1200, 1215, 1230, 1245, 1260, 1275, 1290, 1305,
       1320, 1335, 1350, 1365, 1380, 1395, 1410, 1425, 1440, 1455, 1470,
       1485, 1500, 1515, 1530, 1545, 1560, 1575, 1590, 1605, 1620, 1635,
       1650, 1665, 1680, 1695, 1710, 1725, 1740, 1755, 1770, 1785, 1800,
       1815, 1830, 1845, 1860, 1875, 1890, 1905, 1920, 1935, 1950, 1965,
       1980, 1995, 2010, 2025, 2040, 2055, 2070, 2085, 2100, 2115, 2130,
       2145, 2160, 2175, 2190, 2205, 2220, 2235, 22

In [27]:
print("picks mine", video_mine['picks'][...].shape)
video_mine['picks'][...]

picks mine (146,)


array([   0,   15,   30,   45,   60,   75,   90,  105,  120,  135,  150,
        165,  180,  195,  210,  225,  240,  255,  270,  285,  300,  315,
        330,  345,  360,  375,  390,  405,  420,  435,  450,  465,  480,
        495,  510,  525,  540,  555,  570,  585,  600,  615,  630,  645,
        660,  675,  690,  705,  720,  735,  750,  765,  780,  795,  810,
        825,  840,  855,  870,  885,  900,  915,  930,  945,  960,  975,
        990, 1005, 1020, 1035, 1050, 1065, 1080, 1095, 1110, 1125, 1140,
       1155, 1170, 1185, 1200, 1215, 1230, 1245, 1260, 1275, 1290, 1305,
       1320, 1335, 1350, 1365, 1380, 1395, 1410, 1425, 1440, 1455, 1470,
       1485, 1500, 1515, 1530, 1545, 1560, 1575, 1590, 1605, 1620, 1635,
       1650, 1665, 1680, 1695, 1710, 1725, 1740, 1755, 1770, 1785, 1800,
       1815, 1830, 1845, 1860, 1875, 1890, 1905, 1920, 1935, 1950, 1965,
       1980, 1995, 2010, 2025, 2040, 2055, 2070, 2085, 2100, 2115, 2130,
       2145, 2160, 2175])

### Steps

In [28]:
# print("n steps gt", video_gt['n_steps'][...])
# video_gt['n_steps'][...]

In [29]:
print("n steps mine", video_mine['n_steps'][...])
video_mine['n_steps'][...]

n steps mine 146


array(146)

### Features rn

In [30]:
print("features_rn", video_mine['features_rn'][...].shape)
video_mine['features_rn'][...]

features_rn (146, 2048)


array([[0.71511531, 0.06485288, 0.0638896 , ..., 0.95469522, 0.56251174,
        0.57087553],
       [0.69789821, 0.06702434, 0.06371719, ..., 1.10917819, 0.32317865,
        0.75849539],
       [0.78254682, 0.08371394, 0.07986345, ..., 1.14244437, 0.66674906,
        0.83435261],
       ...,
       [0.51331532, 0.04980703, 0.06310081, ..., 0.75368077, 0.2542994 ,
        0.50618345],
       [0.34196192, 0.07306229, 0.06567524, ..., 0.87150711, 0.29610679,
        0.51421213],
       [0.31442273, 0.04319201, 0.06076743, ..., 0.8455199 , 0.3720665 ,
        0.55019629]])

### Features iv3

In [31]:
print("features_iv3", video_mine['features_iv3'][...].shape)
video_mine['features_iv3'][...]

features_iv3 (146, 2048)


array([[3.98206353e-01, 2.00700939e-01, 1.84082240e-01, ...,
        3.98107022e-02, 6.65887296e-02, 2.85191298e-01],
       [3.52928996e-01, 1.78393945e-01, 2.83144414e-01, ...,
        5.55645823e-02, 6.18357956e-02, 2.45385945e-01],
       [3.64014030e-01, 3.06907594e-01, 2.65186697e-01, ...,
        1.12055697e-01, 8.84462520e-02, 2.34728441e-01],
       ...,
       [1.20676674e-01, 2.20875800e-01, 2.99868695e-02, ...,
        1.35919917e-02, 5.48151834e-03, 9.47642028e-02],
       [1.29023135e-01, 2.17791170e-01, 2.57652774e-02, ...,
        2.04700567e-02, 3.12129239e-04, 5.66731542e-02],
       [1.90694690e-01, 1.51397184e-01, 6.90476149e-02, ...,
        2.79050656e-02, 1.95663385e-02, 1.23461075e-01]])

### Features RGB

In [32]:
print("features_rgb", video_mine['features_rgb'][...].shape)
video_mine['features_rgb'][...]

features_rgb (130, 1024)


array([[1.02239144, 0.09475365, 0.36987996, ..., 0.14193138, 0.91781342,
        0.43479955],
       [0.99051893, 0.1071737 , 0.44474044, ..., 0.18935044, 0.97954434,
        0.22186629],
       [1.00843334, 0.08791192, 0.46448237, ..., 0.14466675, 0.82539284,
        0.26764905],
       ...,
       [0.26584738, 0.1072012 , 0.21930064, ..., 0.12632759, 0.62150794,
        0.50906628],
       [0.28775185, 0.12233169, 0.1931383 , ..., 0.24250858, 0.57057983,
        0.49617204],
       [0.36067691, 0.12579411, 0.20414454, ..., 0.12504935, 0.62676823,
        0.35383326]])

### Features flow

In [33]:
print("features_flow", video_mine['features_flow'][...].shape)
video_mine['features_flow'][...]

features_flow (129, 1024)


array([[1.40366983e-02, 0.00000000e+00, 1.39358625e-01, ...,
        0.00000000e+00, 8.99738744e-02, 0.00000000e+00],
       [1.61132179e-02, 0.00000000e+00, 1.39573723e-01, ...,
        2.60744267e-03, 4.26568240e-02, 0.00000000e+00],
       [1.38228899e-02, 0.00000000e+00, 1.33573949e-01, ...,
        1.20662933e-03, 7.09191896e-03, 0.00000000e+00],
       ...,
       [2.60481611e-02, 0.00000000e+00, 1.93053052e-01, ...,
        1.15041225e-03, 1.16451256e-01, 7.65278563e-03],
       [2.80995108e-02, 0.00000000e+00, 1.95912302e-01, ...,
        1.68760045e-04, 1.01454854e-01, 0.00000000e+00],
       [1.83466654e-02, 0.00000000e+00, 2.09819525e-01, ...,
        9.94437374e-04, 8.57571512e-02, 0.00000000e+00]])

### Features 3D

In [34]:
print("features_3D", video_mine['features_3D'][...].shape)
video_mine['features_3D'][...]

features_3D (130, 2048)


array([[2.00838232, 0.18817014, 1.08919621, ..., 0.55932772, 0.25873041,
        0.40661752],
       [2.11291337, 0.18926652, 1.0041064 , ..., 0.55506998, 0.26807085,
        0.47319746],
       [2.24388933, 0.19824626, 1.0175283 , ..., 0.66117221, 0.23947836,
        0.53313738],
       ...,
       [2.34460402, 1.21669078, 1.27231264, ..., 0.63521028, 0.12973116,
        0.06679551],
       [2.10488081, 1.00556982, 1.19270277, ..., 0.58880442, 0.10537085,
        0.08183762],
       [2.07699704, 0.98862058, 0.99974483, ..., 0.58996546, 0.1587577 ,
        0.23049015]])

SumMe: video name is stored in video_i/video_name.
TVSum: video1-50 corresponds to the same order in ydata-tvsum50.mat, which is the original matlab file provided by TVSum.

In [29]:
#segmentos de 4.5 seg en promedio

In [30]:
4.5*30

135.0

In [21]:
import numpy as np

In [22]:
import os

In [23]:
import cv2

In [24]:
path_data = "/data/shuaman/video_summarization/datasets/raw_datasets/VSUMM/newUserSummary"

In [129]:
name_video = "v71"

In [130]:
path_video = f"/data/shuaman/video_summarization/datasets/raw_datasets/VSUMM/new_database/{name_video}.avi"

In [131]:
path_video

'/data/shuaman/video_summarization/datasets/raw_datasets/VSUMM/new_database/v71.avi'

In [137]:
video_capture = cv2.VideoCapture(path_video)

In [138]:
fps = video_capture.get(cv2.CAP_PROP_FPS)

In [139]:
fps

29.916666666666668

In [140]:
n_frames = int(video_capture.get(cv2.CAP_PROP_FRAME_COUNT))

In [141]:
n_frames

8228

In [113]:
"xd.JPEG".lower().endswith(("png","jpeg","jpg"))

True

In [114]:
fps

29.97002997002997

In [115]:
os.listdir("/data/shuaman/video_summarization/datasets/raw_datasets/VSUMM/new_database/")

['v92.avi',
 'v83.avi',
 'v75.avi',
 'v105.avi',
 'v99.avi',
 'v93.avi',
 'v86.avi',
 'v102.avi',
 'v108.avi',
 'v100.avi',
 'v90.avi',
 'v73.avi',
 'v103.avi',
 'v78.avi',
 'v80.avi',
 'v98.avi',
 'v91.avi',
 'Thumbs.db',
 'v79.avi',
 'v84.avi',
 'v76.avi',
 'v71.avi',
 'v107.avi',
 'v87.avi',
 'v95.avi',
 'v94.avi',
 'v89.avi',
 'v97.avi',
 'v110.avi',
 'v104.avi',
 'v77.avi',
 'v96.avi',
 'v82.avi',
 'v81.avi',
 'v72.avi',
 'v101.avi',
 'v74.avi',
 'v85.avi',
 'v88.avi',
 'v106.avi']

In [116]:
[gtvideo for gtvideo in os.listdir(path_data) if os.path.isdir(os.path.join(path_data, gtvideo))]

['v86',
 'v81',
 'v91',
 'v76',
 'v106',
 'v72',
 'v101',
 'v95',
 'v87',
 'v107',
 'v82',
 'v99',
 'v83',
 'v102',
 'v104',
 'v74',
 'v78',
 'v85',
 'v93',
 'v73',
 'v75',
 'v100',
 'v105',
 'v108',
 'v90',
 'v94',
 'v71',
 'v89',
 'v92',
 'v84',
 'v96',
 'v103',
 'v88',
 'v77',
 'v97',
 'v98',
 'v80',
 'v79',
 'v110']

In [117]:
user_list = os.listdir(os.path.join(path_data, name_video))

In [118]:
user_list

['user1', 'user3', 'user5', 'user4', 'user2']