In [1]:
import pandas as pd

In [2]:
import h5py

In [3]:
import scipy.io

In [4]:
path_just_generated = "/home/shuaman/video_sm/video_summarization/src/eccv16_dataset_ovp_google_pool5.h5"


In [5]:
data_all_ovp_mine = h5py.File(path_just_generated, 'r')

In [6]:
#path_data_preprocessd = "/data/shuaman/video_summarization/datasets/dsnet/datasets/eccv16_dataset_summe_google_pool5.h5"
path_data_preprocessd = "/data/shuaman/video_summarization/datasets/dsnet/datasets/eccv16_dataset_ovp_google_pool5.h5"

In [7]:
data_all_ovp = h5py.File(path_data_preprocessd, 'r')

In [8]:
for i in range(0,50):
    video_gt = data_all_ovp["video_" + str(i+1)]
    video_mine = data_all_ovp_mine["video_" + str(i+1)]
    
    perfect = True
    
    print(f'video {i+1} comparison')
    if video_gt['features'][...].shape != video_mine['features'][...].shape:
        perfect = False
        print("features gt", video_gt['features'][...].shape)
        print("features mine", video_mine['features'][...].shape)
        print()
        
    if video_gt['gtscore'][...].shape != video_mine['gtscore'][...].shape:
        perfect = False
        print("gtscore gt", video_gt['gtscore'][...].shape)
        print("gtscore mine", video_mine['gtscore'][...].shape)
        print()
        
#     print("video name gt", video_gt['video_name'][...])
    print("video name mine", video_mine['video_name'][...])
    
#     if video_gt['user_summary'][...].shape != video_mine['user_summary'][...].shape:
#         perfect = False
#     print("user summary gt", video_gt['user_summary'][...].shape)
    print("user summary mine", video_mine['user_summary'][...].shape)
    print()
        
    if video_gt['n_frames'][...] != video_mine['n_frames'][...]:
        perfect = False
        print("n frames gt", video_gt['n_frames'][...])
        print("n frames mine", video_mine['n_frames'][...])
        print()
    if video_gt['change_points'][...].shape != video_mine['change_points'][...].shape:  
        perfect = False
        print("change points gt", video_gt['change_points'][...].shape)
        print("change points mine", video_mine['change_points'][...].shape)
        print()
        
    if video_gt['n_frame_per_seg'][...].shape != video_mine['n_frame_per_seg'][...].shape: 
        perfect = False
        print("n frame per seg gt", video_gt['n_frame_per_seg'][...].shape)
        print("n frame per seg mine", video_mine['n_frame_per_seg'][...].shape)
        print()
    
    if video_gt['picks'][...].shape != video_mine['picks'][...].shape:
        perfect = False
        print("picks gt", video_gt['picks'][...].shape)
        print("picks mine", video_mine['picks'][...].shape)
        print()
        
#     if video_gt['n_steps'][...] != video_mine['n_steps'][...]:
#         perfect = False
#     print("n steps gt", video_gt['n_steps'][...])
    print("n steps mine", video_mine['n_steps'][...])
        
    if perfect: 
        print("Everything is perfect")
    print()

video 1 comparison
features gt (219, 1024)
features mine (220, 1024)

gtscore gt (219,)
gtscore mine (220,)

video name mine v21
user summary mine (5, 3291)

n frames gt 3284
n frames mine 3291

change points gt (36, 2)
change points mine (22, 2)

n frame per seg gt (36,)
n frame per seg mine (22,)

picks gt (219,)
picks mine (220,)

n steps mine 220

video 2 comparison
features gt (141, 1024)
features mine (142, 1024)

gtscore gt (141,)
gtscore mine (142,)

video name mine v22
user summary mine (5, 2116)

n frames gt 2114
n frames mine 2116

change points gt (5, 2)
change points mine (15, 2)

n frame per seg gt (5,)
n frame per seg mine (15,)

picks gt (141,)
picks mine (142,)

n steps mine 142

video 3 comparison
features gt (117, 1024)
features mine (118, 1024)

gtscore gt (117,)
gtscore mine (118,)

video name mine v23
user summary mine (5, 1759)

n frames gt 1754
n frames mine 1759

change points gt (18, 2)
change points mine (12, 2)

n frame per seg gt (18,)
n frame per seg mine 

In [216]:
for i in range(0,50):
    video_gt = data_all_ovp["video_" + str(i+1)]
    video_mine = data_all_ovp_mine["video_" + str(i+1)]
    
    perfect = True
    
    print(f'video {i+1} comparison')
    if video_gt['features'][...].shape != video_mine['features'][...].shape:
        perfect = False
        print("features gt", video_gt['features'][...].shape)
        print("features mine", video_mine['features'][...].shape)
        print()
        
    if video_gt['gtscore'][...].shape != video_mine['gtscore'][...].shape:
        perfect = False
        print("gtscore gt", video_gt['gtscore'][...].shape)
        print("gtscore mine", video_mine['gtscore'][...].shape)
        print()
        
#     print("video name gt", video_gt['video_name'][...])
    print("video name mine", video_mine['video_name'][...])
    
#     if video_gt['user_summary'][...].shape != video_mine['user_summary'][...].shape:
#         perfect = False
#     print("user summary gt", video_gt['user_summary'][...].shape)
    print("user summary mine", video_mine['user_summary'][...].shape)
    print()
        
    if video_gt['n_frames'][...] != video_mine['n_frames'][...]:
        perfect = False
        print("n frames gt", video_gt['n_frames'][...])
        print("n frames mine", video_mine['n_frames'][...])
        print()
    if video_gt['change_points'][...].shape != video_mine['change_points'][...].shape:  
        perfect = False
        print("change points gt", video_gt['change_points'][...].shape)
        print("change points mine", video_mine['change_points'][...].shape)
        print()
        
    if video_gt['n_frame_per_seg'][...].shape != video_mine['n_frame_per_seg'][...].shape: 
        perfect = False
        print("n frame per seg gt", video_gt['n_frame_per_seg'][...].shape)
        print("n frame per seg mine", video_mine['n_frame_per_seg'][...].shape)
        print()
    
    if video_gt['picks'][...].shape != video_mine['picks'][...].shape:
        perfect = False
        print("picks gt", video_gt['picks'][...].shape)
        print("picks mine", video_mine['picks'][...].shape)
        print()
        
#     if video_gt['n_steps'][...] != video_mine['n_steps'][...]:
#         perfect = False
#     print("n steps gt", video_gt['n_steps'][...])
    print("n steps mine", video_mine['n_steps'][...])
        
    if perfect: 
        print("Everything is perfect")
    print()

video 1 comparison
features gt (219, 1024)
features mine (220, 1024)

gtscore gt (219,)
gtscore mine (220,)

video name mine v21
user summary mine (5, 3291)

n frames gt 3284
n frames mine 3291

change points gt (36, 2)
change points mine (22, 2)

n frame per seg gt (36,)
n frame per seg mine (22,)

picks gt (219,)
picks mine (220,)

n steps mine 220

video 2 comparison
features gt (141, 1024)
features mine (142, 1024)

gtscore gt (141,)
gtscore mine (142,)

video name mine v22
user summary mine (5, 2116)

n frames gt 2114
n frames mine 2116

change points gt (5, 2)
change points mine (15, 2)

n frame per seg gt (5,)
n frame per seg mine (15,)

picks gt (141,)
picks mine (142,)

n steps mine 142

video 3 comparison
features gt (117, 1024)
features mine (118, 1024)

gtscore gt (117,)
gtscore mine (118,)

video name mine v23
user summary mine (5, 1759)

n frames gt 1754
n frames mine 1759

change points gt (18, 2)
change points mine (12, 2)

n frame per seg gt (18,)
n frame per seg mine 

# Evaluating a random video

In [9]:
len(list(data_all_ovp.keys()))

50

In [10]:
#video 1
i = 0
video_gt = data_all_ovp["video_" + str(i+1)]
video_mine = data_all_ovp_mine["video_" + str(i+1)]

### Nombre

In [11]:
# print("video name gt", video_gt['video_name'][...])
print("video name mine", video_mine['video_name'][...])
print()


video name mine v21



### Features

In [12]:
print("features gt", video_gt['features'][...].shape)
video_gt['features'][...]

features gt (219, 1024)


array([[0.        , 0.00062152, 0.        , ..., 0.01108968, 0.01207679,
        0.        ],
       [0.        , 0.01560502, 0.        , ..., 0.00872713, 0.03964416,
        0.        ],
       [0.        , 0.00202694, 0.        , ..., 0.00171111, 0.01888491,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.01176213, 0.        ,
        0.        ],
       [0.        , 0.        , 0.00015808, ..., 0.02377647, 0.        ,
        0.        ],
       [0.00225583, 0.        , 0.01494511, ..., 0.01194581, 0.        ,
        0.        ]])

In [13]:
print("features mine", video_mine['features'][...].shape)
video_mine['features'][...]

features mine (220, 1024)


array([[0.22323546, 0.12151907, 0.41137213, ..., 0.29724649, 0.35464236,
        0.66033018],
       [0.1653274 , 0.07092553, 0.40888509, ..., 0.16038325, 0.52080303,
        0.12615219],
       [0.27510533, 0.19997217, 0.55860341, ..., 0.1485184 , 0.30246037,
        0.5492686 ],
       ...,
       [0.19757941, 0.0051453 , 0.13166626, ..., 0.10935496, 0.11587464,
        0.00076944],
       [0.1100558 , 0.00789383, 0.04138117, ..., 0.61744231, 0.07577407,
        0.08793726],
       [0.10561559, 0.04970843, 0.00086243, ..., 0.09516167, 0.28783232,
        0.00139053]])

### GTScore

In [14]:
print("gtscore gt", video_gt['gtscore'][...].shape)
video_gt['gtscore'][...]

gtscore gt (219,)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
print("gtscore mine", video_mine['gtscore'][...].shape)
video_mine['gtscore'][...]

gtscore mine (220,)


array([0.2       , 0.2       , 0.2       , 0.2       , 0.2       ,
       0.2       , 0.2       , 0.2       , 0.2       , 0.2       ,
       0.2       , 0.2       , 0.2       , 0.2       , 0.2       ,
       0.        , 0.        , 0.        , 0.        , 0.60000002,
       0.60000002, 0.60000002, 0.        , 0.        , 0.        ,
       0.        , 0.60000002, 0.60000002, 0.60000002, 0.60000002,
       0.60000002, 0.60000002, 0.60000002, 0.60000002, 0.60000002,
       0.60000002, 0.60000002, 0.60000002, 0.60000002, 0.60000002,
       0.60000002, 0.60000002, 0.60000002, 0.40000001, 0.40000001,
       0.40000001, 0.40000001, 0.40000001, 0.40000001, 0.40000001,
       0.40000001, 0.60000002, 0.60000002, 0.60000002, 0.60000002,
       0.60000002, 0.60000002, 0.60000002, 0.40000001, 0.40000001,
       0.40000001, 0.40000001, 0.40000001, 0.40000001, 0.80000001,
       0.80000001, 0.80000001, 0.80000001, 0.80000001, 0.80000001,
       0.80000001, 0.80000001, 0.80000001, 0.80000001, 0.     

### User summary

In [16]:
# print("user summary gt", video_gt['user_summary'][...].shape)
# video_gt['user_summary'][...]

In [17]:
print("user summary mine", video_mine['user_summary'][...].shape)
video_mine['user_summary'][...]

user summary mine (5, 3291)


array([[1., 1., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 1., 1., 1.]])

### N frames

In [18]:
print("n frames gt", video_gt['n_frames'][...])

n frames gt 3284


In [19]:
print("n frames mine", video_mine['n_frames'][...])

n frames mine 3291


### Change points

In [20]:
print("change points gt", video_gt['change_points'][...].shape)
video_gt['change_points'][...]

change points gt (36, 2)


array([[   0,   74],
       [  75,  164],
       [ 165,  209],
       [ 210,  254],
       [ 255,  314],
       [ 315,  359],
       [ 360,  629],
       [ 630,  749],
       [ 750,  854],
       [ 855,  944],
       [ 945, 1094],
       [1095, 1229],
       [1230, 1379],
       [1380, 1484],
       [1485, 1529],
       [1530, 1604],
       [1605, 1679],
       [1680, 1739],
       [1740, 1844],
       [1845, 1904],
       [1905, 1979],
       [1980, 2069],
       [2070, 2204],
       [2205, 2279],
       [2280, 2369],
       [2370, 2459],
       [2460, 2534],
       [2535, 2639],
       [2640, 2714],
       [2715, 2759],
       [2760, 2834],
       [2835, 2909],
       [2910, 2984],
       [2985, 3044],
       [3045, 3224],
       [3225, 3283]])

In [21]:
print("change points mine", video_mine['change_points'][...].shape)
video_mine['change_points'][...]

change points mine (22, 2)


array([[   0,  224],
       [ 225,  284],
       [ 285,  374],
       [ 375,  644],
       [ 645,  764],
       [ 765,  869],
       [ 870,  959],
       [ 960, 1109],
       [1110, 1244],
       [1245, 1409],
       [1410, 1754],
       [1755, 1859],
       [1860, 2084],
       [2085, 2219],
       [2220, 2474],
       [2475, 2549],
       [2550, 2654],
       [2655, 2729],
       [2730, 2774],
       [2775, 2924],
       [2925, 2999],
       [3000, 3290]])

### N frames por segmenot

In [22]:
print("n frame per seg gt", video_gt['n_frame_per_seg'][...].shape)
video_gt['n_frame_per_seg'][...]

n frame per seg gt (36,)


array([ 75,  90,  45,  45,  60,  45, 270, 120, 105,  90, 150, 135, 150,
       105,  45,  75,  75,  60, 105,  60,  75,  90, 135,  75,  90,  90,
        75, 105,  75,  45,  75,  75,  75,  60, 180,  59])

In [23]:
print("n frame per seg mine", video_mine['n_frame_per_seg'][...].shape)
video_mine['n_frame_per_seg'][...]

n frame per seg mine (22,)


array([225,  60,  90, 270, 120, 105,  90, 150, 135, 165, 345, 105, 225,
       135, 255,  75, 105,  75,  45, 150,  75, 291])

### Picks

In [24]:
print("picks gt", video_gt['picks'][...].shape)
video_gt['picks'][...]

picks gt (219,)


array([   0,   15,   30,   45,   60,   75,   90,  105,  120,  135,  150,
        165,  180,  195,  210,  225,  240,  255,  270,  285,  300,  315,
        330,  345,  360,  375,  390,  405,  420,  435,  450,  465,  480,
        495,  510,  525,  540,  555,  570,  585,  600,  615,  630,  645,
        660,  675,  690,  705,  720,  735,  750,  765,  780,  795,  810,
        825,  840,  855,  870,  885,  900,  915,  930,  945,  960,  975,
        990, 1005, 1020, 1035, 1050, 1065, 1080, 1095, 1110, 1125, 1140,
       1155, 1170, 1185, 1200, 1215, 1230, 1245, 1260, 1275, 1290, 1305,
       1320, 1335, 1350, 1365, 1380, 1395, 1410, 1425, 1440, 1455, 1470,
       1485, 1500, 1515, 1530, 1545, 1560, 1575, 1590, 1605, 1620, 1635,
       1650, 1665, 1680, 1695, 1710, 1725, 1740, 1755, 1770, 1785, 1800,
       1815, 1830, 1845, 1860, 1875, 1890, 1905, 1920, 1935, 1950, 1965,
       1980, 1995, 2010, 2025, 2040, 2055, 2070, 2085, 2100, 2115, 2130,
       2145, 2160, 2175, 2190, 2205, 2220, 2235, 22

In [25]:
print("picks mine", video_mine['picks'][...].shape)
video_mine['picks'][...]

picks mine (220,)


array([   0,   15,   30,   45,   60,   75,   90,  105,  120,  135,  150,
        165,  180,  195,  210,  225,  240,  255,  270,  285,  300,  315,
        330,  345,  360,  375,  390,  405,  420,  435,  450,  465,  480,
        495,  510,  525,  540,  555,  570,  585,  600,  615,  630,  645,
        660,  675,  690,  705,  720,  735,  750,  765,  780,  795,  810,
        825,  840,  855,  870,  885,  900,  915,  930,  945,  960,  975,
        990, 1005, 1020, 1035, 1050, 1065, 1080, 1095, 1110, 1125, 1140,
       1155, 1170, 1185, 1200, 1215, 1230, 1245, 1260, 1275, 1290, 1305,
       1320, 1335, 1350, 1365, 1380, 1395, 1410, 1425, 1440, 1455, 1470,
       1485, 1500, 1515, 1530, 1545, 1560, 1575, 1590, 1605, 1620, 1635,
       1650, 1665, 1680, 1695, 1710, 1725, 1740, 1755, 1770, 1785, 1800,
       1815, 1830, 1845, 1860, 1875, 1890, 1905, 1920, 1935, 1950, 1965,
       1980, 1995, 2010, 2025, 2040, 2055, 2070, 2085, 2100, 2115, 2130,
       2145, 2160, 2175, 2190, 2205, 2220, 2235, 22

### Steps

In [26]:
# print("n steps gt", video_gt['n_steps'][...])
# video_gt['n_steps'][...]

In [27]:
print("n steps mine", video_mine['n_steps'][...])
video_mine['n_steps'][...]

n steps mine 220


array(220)

SumMe: video name is stored in video_i/video_name.
TVSum: video1-50 corresponds to the same order in ydata-tvsum50.mat, which is the original matlab file provided by TVSum.

In [ ]:
segmentos de 4.5 seg en promedio

In [27]:
4.5*30

135.0

In [30]:
import numpy as np

In [31]:
import os

In [32]:
import cv2

In [33]:
path_data = "/data/shuaman/video_summarization/datasets/raw_datasets/VSUMM/UserSummary"

In [34]:
name_video = "v21"

In [35]:
path_video = f"/data/shuaman/video_summarization/datasets/raw_datasets/VSUMM/database/{name_video}.mpg"

In [36]:
path_video

'/data/shuaman/video_summarization/datasets/raw_datasets/VSUMM/database/v21.mpg'

In [37]:
video_capture = cv2.VideoCapture(path_video)

In [38]:
fps = video_capture.get(cv2.CAP_PROP_FPS)
fps

29.97002997002997

In [39]:
os.listdir("/data/shuaman/video_summarization/datasets/raw_datasets/VSUMM/database/")

['v60.mpg',
 'v32.mpg',
 'v45.mpg',
 'v36.mpg',
 'v34.mpg',
 'v68.mpg',
 'v28.mpg',
 'v24.mpg',
 'v22.mpg',
 'v58.mpg',
 'v30.mpg',
 'v63.mpg',
 'v52.mpg',
 'v41.mpg',
 'v23.mpg',
 'v69.mpg',
 'v35.mpg',
 'v70.mpg',
 'v59.mpg',
 'v62.mpg',
 'v55.mpg',
 'v48.mpg',
 'v57.mpg',
 'v40.mpg',
 'v29.mpg',
 'v54.mpg',
 'v44.mpg',
 'v38.mpg',
 'v47.mpg',
 'v21.mpg',
 'v33.mpg',
 'v51.mpg',
 'v27.mpg',
 'v65.mpg',
 'v49.mpg',
 'v25.mpg',
 'v56.mpg',
 'v53.mpg',
 'v26.mpg',
 'v61.mpg',
 'v37.mpg',
 'v46.mpg',
 'v67.mpg',
 'v64.mpg',
 'v43.mpg',
 'v39.mpg',
 'v42.mpg',
 'v66.mpg',
 'v50.mpg',
 'v31.mpg']

In [40]:
[gtvideo for gtvideo in os.listdir(path_data) if os.path.isdir(os.path.join(path_data, gtvideo))]

['v65',
 'v51',
 'v43',
 'v22',
 'v58',
 'v45',
 'v32',
 'v50',
 'v61',
 'v27',
 'v29',
 'v54',
 'v63',
 'v36',
 'v37',
 'v57',
 'v41',
 'v44',
 'v30',
 'v56',
 'v38',
 'v42',
 'v70',
 'v33',
 'v52',
 'v55',
 'v64',
 'v31',
 'v21',
 'v24',
 'v62',
 'v59',
 'v40',
 'v26',
 'v69',
 'v66',
 'v25',
 'v35',
 'v60',
 'v28',
 'v53',
 'v68',
 'v48',
 'v23',
 'v49',
 'v39',
 'v34',
 'v47',
 'v67',
 'v46']

In [41]:
user_list = os.listdir(os.path.join(path_data, name_video))

In [42]:
user_list

['user1', 'user3', 'user5', 'user4', 'user2']

In [58]:
user_summary = []
for user_summ in np.sort(user_list):
    print(os.listdir(os.path.join(path_data, name_video, user_summ)))
    print(np.sort([int(frame.split('.')[0][5:]) for frame in os.listdir(os.path.join(path_data, name_video, user_summ))]))
    print()
    list_summ = [int(np.ceil(int(frame.split('.')[0][5:])*5.2)) for frame in os.listdir(os.path.join(path_data, name_video, user_summ))]
    list_summ.sort()
    user_summary.append(list_summ)

['Frame2521.jpeg', 'Frame841.jpeg', 'Frame421.jpeg', 'Frame931.jpeg', 'Frame2731.jpeg', 'Frame121.jpeg', 'Frame1081.jpeg', 'Frame2101.jpeg', 'Frame2041.jpeg', 'Frame721.jpeg', 'Frame301.jpeg']
[ 121  301  421  721  841  931 1081 2041 2101 2521 2731]

['Frame3060.jpeg', 'Frame780.jpeg', 'Frame961.jpeg', 'Frame2101.jpeg', 'Frame301.jpeg']
[ 301  780  961 2101 3060]

['Frame1321.jpeg', 'Frame841.jpeg', 'Frame631.jpeg', 'Frame961.jpeg', 'Frame2101.jpeg', 'Frame2671.jpeg', 'Frame1921.jpeg', 'Frame1771.jpeg', 'Frame2912.jpeg']
[ 631  841  961 1321 1771 1921 2101 2671 2912]

['Frame1350.jpeg', 'Frame1711.jpeg', 'Frame2731.jpeg', 'Frame1591.jpeg', 'Frame871.jpeg', 'Frame2041.jpeg', 'Frame721.jpeg', 'Frame301.jpeg', 'Frame3211.jpeg']
[ 301  721  871 1350 1591 1711 2041 2731 3211]

['Frame2011.jpeg', 'Frame3151.jpeg', 'Frame961.jpeg', 'Frame2101.jpeg', 'Frame571.jpeg']
[ 571  961 2011 2101 3151]



In [59]:
user_summary

[[630, 1566, 2190, 3750, 4374, 4842, 5622, 10614, 10926, 13110, 14202],
 [1566, 4056, 4998, 10926, 15912],
 [3282, 4374, 4998, 6870, 9210, 9990, 10926, 13890, 15143],
 [1566, 3750, 4530, 7020, 8274, 8898, 10614, 14202, 16698],
 [2970, 4998, 10458, 10926, 16386]]

In [49]:
user_summary

[[121, 301, 421, 721, 841, 931, 1081, 2041, 2101, 2521, 2731],
 [301, 780, 961, 2101, 3060],
 [631, 841, 961, 1321, 1771, 1921, 2101, 2671, 2912],
 [301, 721, 871, 1350, 1591, 1711, 2041, 2731, 3211],
 [571, 961, 2011, 2101, 3151]]

In [106]:
cp_dummy = video_gt['change_points'][...]

In [121]:
 new_gt_user = np.zeros(n_frames)

In [158]:
segments = [segment for segment in cp_dummy for frame in user_summary[0] if (frame>=segment[0]) and (frame<=segment[1])]
segments

[array([ 75, 164]),
 array([255, 314]),
 array([360, 629]),
 array([630, 749]),
 array([750, 854]),
 array([855, 944]),
 array([ 945, 1094]),
 array([1980, 2069]),
 array([2070, 2204]),
 array([2460, 2534]),
 array([2715, 2759])]

In [159]:
segments[0][0]

75

In [129]:
new_gt_user[segments[0][0]:segments[0][1]+1] = 1

In [130]:
new_gt_user[627:]

array([1., 1., 1., ..., 0., 0., 0.])

In [107]:
cp_dummy

array([[   0,   74],
       [  75,  164],
       [ 165,  209],
       [ 210,  254],
       [ 255,  314],
       [ 315,  359],
       [ 360,  629],
       [ 630,  749],
       [ 750,  854],
       [ 855,  944],
       [ 945, 1094],
       [1095, 1229],
       [1230, 1379],
       [1380, 1484],
       [1485, 1529],
       [1530, 1604],
       [1605, 1679],
       [1680, 1739],
       [1740, 1844],
       [1845, 1904],
       [1905, 1979],
       [1980, 2069],
       [2070, 2204],
       [2205, 2279],
       [2280, 2369],
       [2370, 2459],
       [2460, 2534],
       [2535, 2639],
       [2640, 2714],
       [2715, 2759],
       [2760, 2834],
       [2835, 2909],
       [2910, 2984],
       [2985, 3044],
       [3045, 3224],
       [3225, 3283]])

In [108]:
n_frames = 3284

In [161]:
gt_video = []
for user in user_summary:
    new_gt_user = np.zeros(n_frames)
    segments = [segment for segment in cp_dummy for frame in user if (frame>=segment[0]) and (frame<=segment[1])]
    for segment in segments:
        new_gt_user[int(segment[0]):int(segment[1]+1)] = 1
    gt_video.append(new_gt_user)

In [166]:
gt_video.shape

AttributeError: 'list' object has no attribute 'shape'

In [171]:
np.array(gt_video).T.T.shape[1]

3284

In [164]:
np.array(gt_video)[0][2745:2770]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [115]:
np.zeros(3284)

array([0., 0., 0., ..., 0., 0., 0.])